'use strict';

let current = null;
const used = new Set();

function normalize(text = '') {
  return String(text)
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const preguntas = [
  { q: '¿Capital de Perú?', a: ['lima'] },
  { q: '¿Capital de México?', a: ['ciudad de mexico', 'cdmx', 'mexico df'] },
  { q: '¿Capital de España?', a: ['madrid'] },
  { q: '¿Capital de Argentina?', a: ['buenos aires'] },
  { q: '¿Capital de Chile?', a: ['santiago', 'santiago de chile'] },

  { q: '¿Cuánto es 5 + 7?', a: ['12', 'doce'] },
  { q: '¿Cuánto es 9 x 3?', a: ['27', 'veintisiete'] },
  { q: '¿Cuánto es 15 - 6?', a: ['9', 'nueve'] },
  { q: '¿Cuánto es 8 x 8?', a: ['64', 'sesenta y cuatro'] },
  { q: '¿Cuánto es 100 / 10?', a: ['10', 'diez'] },

  { q: '¿Planeta rojo?', a: ['marte'] },
  { q: '¿Planeta más grande?', a: ['jupiter'] },
  { q: '¿Planeta más cercano al sol?', a: ['mercurio'] },
  { q: '¿Nuestro planeta?', a: ['tierra'] },
  { q: '¿Satélite natural de la Tierra?', a: ['luna'] },

  { q: '¿Color del cielo?', a: ['azul'] },
  { q: '¿Color de la sangre?', a: ['rojo'] },
  { q: '¿Color del pasto?', a: ['verde'] },
  { q: '¿Color del sol?', a: ['amarillo'] },
  { q: '¿Color del carbón?', a: ['negro'] },

  { q: '¿Animal que ladra?', a: ['perro'] },
  { q: '¿Animal que maúlla?', a: ['gato'] },
  { q: '¿Animal más grande del mundo?', a: ['ballena azul'] },
  { q: '¿Animal que vuela y canta?', a: ['pajaro', 'ave'] },
  { q: '¿Animal con trompa?', a: ['elefante'] },

  { q: '¿Idioma de Brasil?', a: ['portugues'] },
  { q: '¿Idioma de Perú?', a: ['espanol', 'castellano'] },
  { q: '¿Idioma de Francia?', a: ['frances'] },
  { q: '¿Idioma de Japón?', a: ['japones'] },
  { q: '¿Idioma de Alemania?', a: ['aleman'] },

  { q: '¿Día después del lunes?', a: ['martes'] },
  { q: '¿Primer día de la semana?', a: ['lunes'] },
  { q: '¿Último día de la semana?', a: ['domingo'] },
  { q: '¿Mes con 28 días?', a: ['febrero'] },
  { q: '¿Cuántos meses tiene el año?', a: ['12', 'doce'] },

  { q: '¿Quién pintó la Mona Lisa?', a: ['da vinci', 'leonardo da vinci'] },
  { q: '¿Autor de Harry Potter?', a: ['rowling', 'jk rowling', 'j k rowling'] },
  { q: '¿Creador de Facebook?', a: ['mark zuckerberg', 'zuckerberg'] },
  { q: '¿Fundador de Apple?', a: ['steve jobs', 'jobs'] },
  { q: '¿Creador de Microsoft?', a: ['bill gates', 'gates'] },

  { q: '¿Cuántos lados tiene un triángulo?', a: ['3', 'tres'] },
  { q: '¿Cuántos lados tiene un cuadrado?', a: ['4', 'cuatro'] },
  { q: '¿Cuántos lados tiene un pentágono?', a: ['5', 'cinco'] },
  { q: '¿Cuántos lados tiene un hexágono?', a: ['6', 'seis'] },
  { q: '¿Cuántos lados tiene un círculo?', a: ['0', 'cero', 'ninguno'] },

  { q: '¿Metal precioso amarillo?', a: ['oro'] },
  { q: '¿Metal usado en cables?', a: ['cobre'] },
  { q: '¿Gas que respiramos?', a: ['oxigeno'] },
  { q: '¿Gas que absorben las plantas?', a: ['dioxido de carbono', 'co2'] },
  { q: '¿Elemento del agua?', a: ['hidrogeno'] },

  { q: '¿Qué app es de mensajería verde?', a: ['whatsapp'] },
  { q: '¿App para fotos?', a: ['instagram'] },
  { q: '¿App de videos cortos?', a: ['tiktok'] },
  { q: '¿App de streaming?', a: ['netflix'] },
  { q: '¿Buscador más usado?', a: ['google'] },

  { q: '¿Juego de bloques famoso?', a: ['minecraft'] },
  { q: '¿Juego battle royale famoso?', a: ['fortnite'] },
  { q: '¿Juego de fútbol famoso?', a: ['fifa', 'ea sports fc'] },
  { q: '¿Fontanero de Nintendo?', a: ['mario', 'super mario'] },
  { q: '¿Erizo azul?', a: ['sonic'] },

  { q: '¿Protagonista de Naruto?', a: ['naruto'] },
  { q: '¿Protagonista de Dragon Ball?', a: ['goku'] },
  { q: '¿Protagonista de One Piece?', a: ['luffy'] },
  { q: '¿Pokémon amarillo?', a: ['pikachu'] },
  { q: '¿Cazador de titanes?', a: ['eren', 'eren jaeger', 'eren yeager'] }
];
preguntas.push(
  // 🌎 Geografía
  { q: '¿Capital de Colombia?', a: ['bogota'] },
  { q: '¿Capital de Ecuador?', a: ['quito'] },
  { q: '¿Capital de Bolivia?', a: ['sucre', 'la paz'] },
  { q: '¿Capital de Uruguay?', a: ['montevideo'] },
  { q: '¿Capital de Paraguay?', a: ['asuncion'] },
  { q: '¿Capital de Venezuela?', a: ['caracas'] },
  { q: '¿Capital de Brasil?', a: ['brasilia'] },
  { q: '¿Capital de Estados Unidos?', a: ['washington', 'washington dc'] },
  { q: '¿Capital de Canadá?', a: ['ottawa'] },
  { q: '¿Capital de Italia?', a: ['roma'] },
  { q: '¿Capital de Francia?', a: ['paris'] },
  { q: '¿Capital de Alemania?', a: ['berlin'] },
  { q: '¿Capital de Portugal?', a: ['lisboa'] },
  { q: '¿Capital de Japón?', a: ['tokio', 'tokyo'] },
  { q: '¿Capital de China?', a: ['pekin', 'beijing'] },
  { q: '¿Capital de Corea del Sur?', a: ['seul', 'seoul'] },
  { q: '¿Capital de Rusia?', a: ['moscu'] },
  { q: '¿Capital de Egipto?', a: ['el cairo', 'cairo'] },
  { q: '¿País donde está Machu Picchu?', a: ['peru'] },
  { q: '¿País donde está la Torre Eiffel?', a: ['francia'] },
  { q: '¿País donde está el Coliseo romano?', a: ['italia'] },
  { q: '¿País donde están las pirámides de Giza?', a: ['egipto'] },
  { q: '¿Continente donde está Perú?', a: ['america', 'america del sur', 'sudamerica'] },
  { q: '¿Océano más grande del mundo?', a: ['pacifico', 'oceano pacifico'] },
  { q: '¿Desierto más grande del mundo?', a: ['sahara', 'desierto del sahara'] },

  // 🌍 Países y capitales
{ q: '¿Capital de Noruega?', a: ['oslo'] },
{ q: '¿Capital de Suecia?', a: ['estocolmo'] },
{ q: '¿Capital de Finlandia?', a: ['helsinki'] },
{ q: '¿Capital de Dinamarca?', a: ['copenhague'] },
{ q: '¿Capital de Bélgica?', a: ['bruselas'] },
{ q: '¿Capital de Austria?', a: ['viena'] },
{ q: '¿Capital de Hungría?', a: ['budapest'] },
{ q: '¿Capital de Polonia?', a: ['varsovia'] },
{ q: '¿Capital de Irlanda?', a: ['dublin'] },
{ q: '¿Capital de Islandia?', a: ['reikiavik'] },

// 🧠 Cultura general
{ q: '¿Cuántos continentes existen?', a: ['7', 'siete'] },
{ q: '¿Cuántos océanos existen?', a: ['5', 'cinco'] },
{ q: '¿Cuál es el continente más grande?', a: ['asia'] },
{ q: '¿Cuál es el continente más pequeño?', a: ['oceania'] },
{ q: '¿Cuál es el país más grande del mundo?', a: ['rusia'] },
{ q: '¿Cuál es el país más poblado del mundo?', a: ['india'] },
{ q: '¿Cuál es el idioma más hablado del mundo?', a: ['ingles'] },
{ q: '¿Cuál es la moneda de Estados Unidos?', a: ['dolar'] },
{ q: '¿Cuál es la moneda de Japón?', a: ['yen'] },
{ q: '¿Cuál es la moneda de Europa?', a: ['euro'] },

// 🐾 Animales
{ q: '¿Animal más alto del mundo?', a: ['jirafa'] },
{ q: '¿Animal más pesado de la Tierra?', a: ['ballena azul'] },
{ q: '¿Animal símbolo de Australia?', a: ['canguro'] },
{ q: '¿Animal que produce lana?', a: ['oveja'] },
{ q: '¿Animal que tiene caparazón y pinzas?', a: ['cangrejo'] },
{ q: '¿Animal que vive en colmenas?', a: ['abeja'] },
{ q: '¿Animal conocido por cambiar de color?', a: ['camaleon'] },
{ q: '¿Ave más grande del mundo?', a: ['avestruz'] },
{ q: '¿Mamífero que pone huevos?', a: ['ornitorrinco'] },
{ q: '¿Animal nacional de China?', a: ['panda'] },

// 🎮 Videojuegos
{ q: '¿Empresa creadora de Minecraft?', a: ['mojang'] },
{ q: '¿Nombre del protagonista de Halo?', a: ['master chief'] },
{ q: '¿Personaje principal de God of War?', a: ['kratos'] },
{ q: '¿Criatura principal de Pokémon?', a: ['pikachu'] },
{ q: '¿Juego donde aparecen creepers?', a: ['minecraft'] },
{ q: '¿Empresa creadora de PlayStation?', a: ['sony'] },
{ q: '¿Empresa creadora de Xbox?', a: ['microsoft'] },
{ q: '¿Empresa creadora de Nintendo Switch?', a: ['nintendo'] },
{ q: '¿Juego donde aparece Link?', a: ['zelda'] },
{ q: '¿Juego donde aparece Luigi?', a: ['mario'] },

// 🎬 Cine
{ q: '¿Nombre del mago protagonista de Hogwarts?', a: ['harry potter'] },
{ q: '¿Nombre del mejor amigo pelirrojo de Harry Potter?', a: ['ron weasley'] },
{ q: '¿Nombre de la amiga inteligente de Harry Potter?', a: ['hermione'] },
{ q: '¿Nombre del villano principal de Harry Potter?', a: ['voldemort'] },
{ q: '¿Nombre del padre de Simba?', a: ['mufasa'] },
{ q: '¿Nombre del villano de El Rey León?', a: ['scar'] },
{ q: '¿Nombre del robot de Star Wars dorado?', a: ['c3po'] },
{ q: '¿Nombre del robot azul de Star Wars?', a: ['r2d2'] },
{ q: '¿Nombre del ogro verde famoso?', a: ['shrek'] },
{ q: '¿Nombre del burro amigo de Shrek?', a: ['burro'] },

// ⚽ Deportes
{ q: '¿Cuántos jugadores tiene un equipo de voleibol?', a: ['6', 'seis'] },
{ q: '¿Cuántos tiempos tiene un partido de fútbol?', a: ['2', 'dos'] },
{ q: '¿Deporte de Lionel Messi?', a: ['futbol'] },
{ q: '¿Deporte de Michael Jordan?', a: ['basquetbol', 'baloncesto', 'basket'] },
{ q: '¿Deporte de Rafael Nadal?', a: ['tenis'] },
{ q: '¿Deporte de Usain Bolt?', a: ['atletismo'] },
{ q: '¿País que ganó el Mundial 2022?', a: ['argentina'] },
{ q: '¿Color de la camiseta tradicional de Brasil?', a: ['amarillo'] },
{ q: '¿Cuántos jugadores hay en una cancha de fútbol contando ambos equipos?', a: ['22'] },
{ q: '¿Deporte donde se usa un bate?', a: ['beisbol'] },

// 📱 Tecnología
{ q: '¿Quién fundó Tesla?', a: ['elon musk'] },
{ q: '¿Quién fundó Amazon?', a: ['jeff bezos'] },
{ q: '¿Quién fundó Facebook?', a: ['mark zuckerberg'] },
{ q: '¿Quién fundó Microsoft?', a: ['bill gates'] },
{ q: '¿Quién fundó Apple junto a Steve Wozniak?', a: ['steve jobs'] },
{ q: '¿Qué navegador desarrolla Google?', a: ['chrome'] },
{ q: '¿Qué navegador desarrolla Mozilla?', a: ['firefox'] },
{ q: '¿Qué aplicación compró Facebook en 2014?', a: ['whatsapp'] },
{ q: '¿Qué plataforma es conocida por videos cortos?', a: ['tiktok'] },
{ q: '¿Qué plataforma pertenece a Google?', a: ['youtube'] },

// 🔢 Matemáticas
{ q: '¿Cuánto es 20 x 20?', a: ['400'] },
{ q: '¿Cuánto es 30 x 3?', a: ['90'] },
{ q: '¿Cuánto es 99 + 1?', a: ['100'] },
{ q: '¿Cuánto es 250 - 100?', a: ['150'] },
{ q: '¿Cuánto es 1000 / 10?', a: ['100'] },
{ q: '¿Cuánto es 7 x 11?', a: ['77'] },
{ q: '¿Cuánto es 14 x 4?', a: ['56'] },
{ q: '¿Cuánto es 18 + 18?', a: ['36'] },
{ q: '¿Cuánto es 90 / 9?', a: ['10'] },
{ q: '¿Cuánto es 5 x 12?', a: ['60'] },

// 🎵 Música
{ q: '¿Instrumento con 88 teclas?', a: ['piano'] },
{ q: '¿Instrumento de viento de metal muy usado en jazz?', a: ['trompeta'] },
{ q: '¿Instrumento de cuerda más pequeño que el violonchelo?', a: ['violin'] },
{ q: '¿Instrumento típico de Escocia?', a: ['gaita'] },
{ q: '¿Grupo británico de John Lennon?', a: ['the beatles', 'beatles'] },
{ q: '¿Rey del pop?', a: ['michael jackson'] },
{ q: '¿Cantante de Thriller?', a: ['michael jackson'] },
{ q: '¿Cantante conocida como Reina del Pop?', a: ['madonna'] },
{ q: '¿Aplicación famosa para escuchar música?', a: ['spotify'] },
{ q: '¿Instrumento que tiene cuerdas y se toca con arco?', a: ['violin'] },

// 🤔 Lógica
{ q: '¿Cuántos meses tienen 28 días o más?', a: ['12', 'doce'] },
{ q: '¿Qué sube pero nunca baja?', a: ['edad'] },
{ q: '¿Qué tiene agujas pero no cose?', a: ['reloj'] },
{ q: '¿Qué tiene dientes pero no muerde?', a: ['peine'] },
{ q: '¿Qué tiene ojos pero no ve?', a: ['papa'] },
{ q: '¿Qué se rompe al decir su nombre?', a: ['silencio'] },
{ q: '¿Qué corre pero no tiene piernas?', a: ['agua'] },
{ q: '¿Qué tiene cuello pero no cabeza?', a: ['botella'] },
{ q: '¿Qué tiene llaves pero no abre puertas?', a: ['piano'] },
{ q: '¿Qué puede viajar por el mundo sin moverse?', a: ['sello postal', 'estampilla'] },

  // 🧮 Matemáticas
  { q: '¿Cuánto es 6 + 6?', a: ['12', 'doce'] },
  { q: '¿Cuánto es 7 + 8?', a: ['15', 'quince'] },
  { q: '¿Cuánto es 20 - 9?', a: ['11', 'once'] },
  { q: '¿Cuánto es 14 + 6?', a: ['20', 'veinte'] },
  { q: '¿Cuánto es 12 x 2?', a: ['24', 'veinticuatro'] },
  { q: '¿Cuánto es 11 x 3?', a: ['33', 'treinta y tres'] },
  { q: '¿Cuánto es 10 x 10?', a: ['100', 'cien'] },
  { q: '¿Cuánto es 50 / 5?', a: ['10', 'diez'] },
  { q: '¿Cuánto es 81 / 9?', a: ['9', 'nueve'] },
  { q: '¿Cuánto es 3 al cuadrado?', a: ['9', 'nueve'] },
  { q: '¿Cuánto es 5 al cuadrado?', a: ['25', 'veinticinco'] },
  { q: '¿Número par después del 8?', a: ['10', 'diez'] },
  { q: '¿Número impar después del 7?', a: ['9', 'nueve'] },
  { q: '¿Cuántos minutos tiene una hora?', a: ['60', 'sesenta'] },
  { q: '¿Cuántos segundos tiene un minuto?', a: ['60', 'sesenta'] },

  // 🧪 Ciencia
  { q: '¿Qué órgano bombea la sangre?', a: ['corazon'] },
  { q: '¿Qué órgano usamos para respirar?', a: ['pulmones', 'pulmon'] },
  { q: '¿Qué órgano usamos para pensar?', a: ['cerebro'] },
  { q: '¿Qué parte del cuerpo usamos para ver?', a: ['ojos', 'ojo'] },
  { q: '¿Qué parte del cuerpo usamos para oír?', a: ['oidos', 'orejas', 'oido'] },
  { q: '¿Qué necesitan las plantas para hacer fotosíntesis?', a: ['luz', 'sol', 'luz solar'] },
  { q: '¿Qué líquido es vital para vivir?', a: ['agua'] },
  { q: '¿Qué gas respiramos principalmente para vivir?', a: ['oxigeno'] },
  { q: '¿Qué estrella ilumina la Tierra?', a: ['sol'] },
  { q: '¿Cómo se llama el cambio de líquido a gas?', a: ['evaporacion'] },
  { q: '¿Cómo se llama el cambio de agua a hielo?', a: ['congelacion'] },
  { q: '¿Qué fuerza nos mantiene pegados al suelo?', a: ['gravedad'] },
  { q: '¿Qué instrumento mide la temperatura?', a: ['termometro'] },
  { q: '¿Qué instrumento sirve para ver cosas muy pequeñas?', a: ['microscopio'] },
  { q: '¿Qué instrumento sirve para ver estrellas lejanas?', a: ['telescopio'] },

  // 🐾 Animales
  { q: '¿Animal conocido como rey de la selva?', a: ['leon'] },
  { q: '¿Animal que da leche?', a: ['vaca'] },
  { q: '¿Animal que pone huevos y cacarea?', a: ['gallina'] },
  { q: '¿Animal que relincha?', a: ['caballo'] },
  { q: '¿Animal que rebuzna?', a: ['burro', 'asno'] },
  { q: '¿Animal que tiene rayas negras y blancas?', a: ['cebra'] },
  { q: '¿Animal que cambia de color?', a: ['camaleon'] },
  { q: '¿Animal que tiene cuello muy largo?', a: ['jirafa'] },
  { q: '¿Animal que produce miel?', a: ['abeja'] },
  { q: '¿Animal que vive en una telaraña?', a: ['arana'] },
  { q: '¿Animal que salta y tiene bolsa?', a: ['canguro'] },
  { q: '¿Animal marino con ocho brazos?', a: ['pulpo'] },
  { q: '¿Animal que nada y tiene aletas?', a: ['pez'] },
  { q: '¿Ave que no puede volar y vive en zonas frías?', a: ['pinguino'] },
  { q: '¿Animal lento con caparazón?', a: ['tortuga'] },

  // 🍎 Comida
  { q: '¿Fruta amarilla que comen los monos?', a: ['platano', 'banana'] },
  { q: '¿Fruta roja asociada a Blancanieves?', a: ['manzana'] },
  { q: '¿Fruta verde por fuera y roja por dentro?', a: ['sandia'] },
  { q: '¿Fruta pequeña usada para hacer vino?', a: ['uva'] },
  { q: '¿Comida italiana redonda con queso?', a: ['pizza'] },
  { q: '¿Comida japonesa con arroz y pescado?', a: ['sushi'] },
  { q: '¿Bebida que se hace con cacao?', a: ['chocolate'] },
  { q: '¿Bebida caliente hecha con granos tostados?', a: ['cafe'] },
  { q: '¿Ingrediente principal del pan?', a: ['harina'] },
  { q: '¿Alimento blanco que viene de la vaca?', a: ['leche'] },

  // 🎬 Películas, series y personajes
  { q: '¿Superhéroe que usa telarañas?', a: ['spiderman', 'hombre arana'] },
  { q: '¿Superhéroe de Gotham?', a: ['batman'] },
  { q: '¿Superhéroe que viene de Krypton?', a: ['superman'] },
  { q: '¿Princesa de hielo de Frozen?', a: ['elsa'] },
  { q: '¿Muñeco vaquero de Toy Story?', a: ['woody'] },
  { q: '¿Robot pequeño de Wall-E?', a: ['wall e', 'walle'] },
  { q: '¿Ogro verde famoso?', a: ['shrek'] },
  { q: '¿Ratón famoso de Disney?', a: ['mickey', 'mickey mouse'] },
  { q: '¿Pato famoso de Disney?', a: ['donald', 'pato donald'] },
  { q: '¿León protagonista de El Rey León?', a: ['simba'] },
  { q: '¿Escuela de magia de Harry Potter?', a: ['hogwarts'] },
  { q: '¿Villano principal de Avengers Infinity War?', a: ['thanos'] },
  { q: '¿Robot amarillo de Transformers?', a: ['bumblebee'] },
  { q: '¿Película de autos con Rayo McQueen?', a: ['cars'] },
  { q: '¿Payaso enemigo de Batman?', a: ['joker', 'guason'] },

  // 🎮 Videojuegos
  { q: '¿Bloque explosivo de Minecraft?', a: ['tnt'] },
  { q: '¿Enemigo verde que explota en Minecraft?', a: ['creeper'] },
  { q: '¿Juego donde se construye con bloques?', a: ['minecraft'] },
  { q: '¿Juego famoso de disparos y construcción?', a: ['fortnite'] },
  { q: '¿Juego donde impostores eliminan tripulantes?', a: ['among us'] },
  { q: '¿Juego de fútbol de EA?', a: ['fifa', 'ea sports fc'] },
  { q: '¿Consola portátil de Nintendo muy famosa?', a: ['switch', 'nintendo switch'] },
  { q: '¿Pokémon inicial de tipo fuego de Kanto?', a: ['charmander'] },
  { q: '¿Pokémon inicial de tipo agua de Kanto?', a: ['squirtle'] },
  { q: '¿Pokémon inicial de tipo planta de Kanto?', a: ['bulbasaur'] },

  // 📱 Tecnología
  { q: '¿Sistema operativo de iPhone?', a: ['ios'] },
  { q: '¿Sistema operativo de muchos celulares Samsung?', a: ['android'] },
  { q: '¿Red social de videos cortos?', a: ['tiktok'] },
  { q: '¿Red social de fotos y reels?', a: ['instagram'] },
  { q: '¿Aplicación de mensajes con logo verde?', a: ['whatsapp'] },
  { q: '¿Plataforma para ver videos largos?', a: ['youtube'] },
  { q: '¿Servicio de música con logo verde?', a: ['spotify'] },
  { q: '¿Empresa creadora de Windows?', a: ['microsoft'] },
  { q: '¿Empresa creadora del iPhone?', a: ['apple'] },
  { q: '¿Empresa creadora de Android?', a: ['google'] },

  // 🏆 Deportes
  { q: '¿Deporte más popular del mundo?', a: ['futbol'] },
  { q: '¿Cuántos jugadores tiene un equipo de fútbol en cancha?', a: ['11', 'once'] },
  { q: '¿Deporte donde se usa una raqueta y una pelota amarilla?', a: ['tenis'] },
  { q: '¿Deporte donde se encesta una pelota?', a: ['basquet', 'basket', 'baloncesto'] },
  { q: '¿Deporte donde se nada en piscina?', a: ['natacion'] },
  { q: '¿Evento deportivo mundial cada 4 años?', a: ['mundial', 'copa mundial', 'mundial de futbol'] },
  { q: '¿Color de tarjeta para expulsión en fútbol?', a: ['roja', 'tarjeta roja'] },
  { q: '¿Color de tarjeta de advertencia en fútbol?', a: ['amarilla', 'tarjeta amarilla'] },
  { q: '¿Objeto que se patea en fútbol?', a: ['pelota', 'balon'] },
  { q: '¿Lugar donde se juega fútbol?', a: ['cancha', 'campo', 'estadio'] },

  // 🎵 Música
  { q: '¿Instrumento con teclas blancas y negras?', a: ['piano'] },
  { q: '¿Instrumento de seis cuerdas?', a: ['guitarra'] },
  { q: '¿Instrumento que se toca con baquetas?', a: ['bateria', 'tambor'] },
  { q: '¿Persona que canta?', a: ['cantante'] },
  { q: '¿Persona que toca música con mezclas?', a: ['dj'] },
  { q: '¿Género musical popular de Puerto Rico?', a: ['reggaeton'] },
  { q: '¿Canción sin voz, solo música?', a: ['instrumental'] },
  { q: '¿Disco con varias canciones?', a: ['album'] },
  { q: '¿Aplicación famosa para escuchar música?', a: ['spotify'] },
  { q: '¿Instrumento pequeño que se sopla y tiene agujeros?', a: ['flauta'] },

  // 📚 Cultura general
  { q: '¿Cuántas letras tiene el abecedario español?', a: ['27', 'veintisiete'] },
  { q: '¿Primera letra del abecedario?', a: ['a'] },
  { q: '¿Última letra del abecedario?', a: ['z'] },
  { q: '¿Cuántas horas tiene un día?', a: ['24', 'veinticuatro'] },
  { q: '¿Cuántos días tiene una semana?', a: ['7', 'siete'] },
  { q: '¿Cuántos días tiene un año normal?', a: ['365', 'trescientos sesenta y cinco'] },
  { q: '¿Qué usamos para escribir en papel?', a: ['lapiz', 'lapicero', 'pluma', 'boligrafo'] },
  { q: '¿Lugar donde se estudia?', a: ['colegio', 'escuela', 'universidad'] },
  { q: '¿Lugar donde se compran medicinas?', a: ['farmacia'] },
  { q: '¿Lugar donde se compran alimentos?', a: ['mercado', 'supermercado', 'tienda'] },

  // 🇵🇪 Perú
  { q: '¿Capital del Perú?', a: ['lima'] },
  { q: '¿Moneda del Perú?', a: ['sol', 'nuevo sol', 'soles'] },
  { q: '¿Comida peruana con pescado y limón?', a: ['ceviche', 'cebiche'] },
  { q: '¿Bebida peruana morada?', a: ['chicha morada'] },
  { q: '¿Inca famoso asociado a Machu Picchu?', a: ['pachacutec'] },
  { q: '¿Baile típico peruano con pañuelo?', a: ['marinera'] },
  { q: '¿Animal andino usado para cargar cosas?', a: ['llama'] },
  { q: '¿Ave símbolo del escudo peruano?', a: ['vicuña', 'vicuna'] },
  { q: '¿Ciudad peruana conocida como Ciudad Blanca?', a: ['arequipa'] },
  { q: '¿Lago compartido por Perú y Bolivia?', a: ['titicaca', 'lago titicaca'] },

  // 😹 Preguntas random/divertidas
  { q: '¿Qué animal dice miau?', a: ['gato'] },
  { q: '¿Qué animal dice guau?', a: ['perro'] },
  { q: '¿Qué emoji representa risa con lágrimas?', a: ['😂', 'carita llorando de risa', 'risa'] },
  { q: '¿Qué se usa para tomar fotos?', a: ['camara', 'celular'] },
  { q: '¿Qué se usa para llamar por teléfono?', a: ['celular', 'telefono'] },
  { q: '¿Qué se prende cuando está oscuro?', a: ['luz', 'linterna', 'foco'] },
  { q: '¿Qué se abre para entrar a una casa?', a: ['puerta'] },
  { q: '¿Qué se usa para dormir?', a: ['cama'] },
  { q: '¿Qué usamos cuando llueve?', a: ['paraguas'] },
  { q: '¿Qué usamos para ver la hora?', a: ['reloj', 'celular'] }
);
preguntas.push(
  // 🌎 Geografía difícil / media
  { q: '¿Cuál es la capital de Australia?', a: ['canberra'] },
  { q: '¿Cuál es la capital de Suiza?', a: ['berna'] },
  { q: '¿Cuál es la capital de Turquía?', a: ['ankara'] },
  { q: '¿Cuál es la capital de Grecia?', a: ['atenas'] },
  { q: '¿Cuál es la capital de India?', a: ['nueva delhi', 'delhi'] },
  { q: '¿Cuál es la capital de Tailandia?', a: ['bangkok'] },
  { q: '¿Cuál es la capital de Marruecos?', a: ['rabat'] },
  { q: '¿Cuál es la capital de Cuba?', a: ['la habana', 'habana'] },
  { q: '¿Cuál es la capital de Costa Rica?', a: ['san jose'] },
  { q: '¿Cuál es la capital de Panamá?', a: ['ciudad de panama', 'panama'] },
  { q: '¿En qué país está el monte Fuji?', a: ['japon'] },
  { q: '¿En qué país está Petra?', a: ['jordania'] },
  { q: '¿En qué país está el Taj Mahal?', a: ['india'] },
  { q: '¿Qué país tiene forma de bota?', a: ['italia'] },
  { q: '¿Qué país es conocido como la tierra del sol naciente?', a: ['japon'] },
  { q: '¿Qué océano separa América de Europa?', a: ['atlantico', 'oceano atlantico'] },
  { q: '¿Qué cordillera atraviesa gran parte de Sudamérica?', a: ['andes', 'cordillera de los andes'] },
  { q: '¿Cuál es la montaña más alta del mundo?', a: ['everest', 'monte everest'] },
  { q: '¿Cuál es el río más famoso de Egipto?', a: ['nilo', 'rio nilo'] },
  { q: '¿Cuál es el desierto más seco del mundo?', a: ['atacama', 'desierto de atacama'] },

  // 🧠 Historia
  { q: '¿Qué civilización construyó Machu Picchu?', a: ['inca', 'incas', 'civilizacion inca'] },
  { q: '¿Qué civilización construyó las pirámides de Egipto?', a: ['egipcia', 'egipcios', 'civilizacion egipcia'] },
  { q: '¿Quién llegó a América en 1492?', a: ['cristobal colon', 'colon'] },
  { q: '¿Cómo se llamaba el barco principal de Cristóbal Colón?', a: ['santa maria', 'la santa maria'] },
  { q: '¿Qué muro dividía Berlín?', a: ['muro de berlin'] },
  { q: '¿Qué imperio tenía emperadores llamados césares?', a: ['imperio romano', 'romano'] },
  { q: '¿Qué cultura antigua usaba jeroglíficos?', a: ['egipcia', 'egipcios'] },
  { q: '¿En qué país ocurrió la Revolución Francesa?', a: ['francia'] },
  { q: '¿Qué ciudad fue sepultada por el volcán Vesubio?', a: ['pompeya'] },
  { q: '¿Quién fue el primer hombre en pisar la Luna?', a: ['neil armstrong', 'armstrong'] },

  // 🧪 Ciencia
  { q: '¿Cuál es la fórmula química del agua?', a: ['h2o'] },
  { q: '¿Cuál es el símbolo químico del oro?', a: ['au'] },
  { q: '¿Cuál es el símbolo químico de la plata?', a: ['ag'] },
  { q: '¿Cuál es el símbolo químico del hierro?', a: ['fe'] },
  { q: '¿Qué planeta tiene anillos muy visibles?', a: ['saturno'] },
  { q: '¿Qué galaxia contiene nuestro sistema solar?', a: ['via lactea'] },
  { q: '¿Cómo se llama el proceso por el que las plantas producen alimento?', a: ['fotosintesis'] },
  { q: '¿Qué parte de la célula contiene el ADN?', a: ['nucleo'] },
  { q: '¿Qué partícula tiene carga negativa?', a: ['electron'] },
  { q: '¿Qué capa protege la Tierra de rayos ultravioleta?', a: ['capa de ozono', 'ozono'] },
  { q: '¿Cuál es el hueso más largo del cuerpo humano?', a: ['femur'] },
  { q: '¿Cuántos huesos tiene el cuerpo humano adulto?', a: ['206', 'doscientos seis'] },
  { q: '¿Qué órgano filtra la sangre y produce orina?', a: ['rinon', 'riñon', 'rinones', 'riñones'] },
  { q: '¿Qué tipo de animal es una rana?', a: ['anfibio'] },
  { q: '¿Qué tipo de animal es una serpiente?', a: ['reptil'] },

  // 🧮 Matemáticas más difíciles
  { q: '¿Cuánto es 12 x 12?', a: ['144', 'ciento cuarenta y cuatro'] },
  { q: '¿Cuánto es 15 x 4?', a: ['60', 'sesenta'] },
  { q: '¿Cuánto es 18 x 3?', a: ['54', 'cincuenta y cuatro'] },
  { q: '¿Cuánto es 7 al cuadrado?', a: ['49', 'cuarenta y nueve'] },
  { q: '¿Cuánto es 9 al cuadrado?', a: ['81', 'ochenta y uno'] },
  { q: '¿Cuál es la raíz cuadrada de 100?', a: ['10', 'diez'] },
  { q: '¿Cuál es la raíz cuadrada de 81?', a: ['9', 'nueve'] },
  { q: '¿Cuánto es la mitad de 250?', a: ['125', 'ciento veinticinco'] },
  { q: '¿Cuánto es el doble de 48?', a: ['96', 'noventa y seis'] },
  { q: '¿Cuánto es el triple de 15?', a: ['45', 'cuarenta y cinco'] },
  { q: '¿Cuánto es 25% de 100?', a: ['25', 'veinticinco'] },
  { q: '¿Cuánto es 50% de 200?', a: ['100', 'cien'] },
  { q: '¿Cuántos grados tiene un ángulo recto?', a: ['90', 'noventa'] },
  { q: '¿Cuántos grados tiene un círculo completo?', a: ['360', 'trescientos sesenta'] },
  { q: '¿Cuánto es 13 x 5?', a: ['65', 'sesenta y cinco'] },

  // 📚 Lenguaje
  { q: '¿Cómo se llama una palabra que significa lo contrario de otra?', a: ['antonimo'] },
  { q: '¿Cómo se llama una palabra con significado parecido a otra?', a: ['sinonimo'] },
  { q: '¿Qué tipo de palabra es “correr”?', a: ['verbo'] },
  { q: '¿Qué tipo de palabra es “casa”?', a: ['sustantivo'] },
  { q: '¿Qué tipo de palabra es “rápido”?', a: ['adjetivo'] },
  { q: '¿Cuál es el plural de “lápiz”?', a: ['lapices'] },
  { q: '¿Cuál es el singular de “luces”?', a: ['luz'] },
  { q: '¿Cómo se llama el conjunto de letras de un idioma?', a: ['abecedario', 'alfabeto'] },
  { q: '¿Qué signo se usa para hacer una pregunta?', a: ['interrogacion', 'signo de interrogacion'] },
  { q: '¿Qué signo se usa para expresar sorpresa?', a: ['exclamacion', 'signo de exclamacion'] },

  // 🐾 Animales
  { q: '¿Cuál es el animal terrestre más rápido?', a: ['guepardo', 'chita'] },
  { q: '¿Qué animal duerme colgado boca abajo?', a: ['murcielago'] },
  { q: '¿Qué animal construye represas?', a: ['castor'] },
  { q: '¿Qué animal tiene tinta para defenderse?', a: ['pulpo', 'calamar'] },
  { q: '¿Qué insecto se convierte en mariposa?', a: ['oruga'] },
  { q: '¿Qué animal es conocido por su memoria?', a: ['elefante'] },
  { q: '¿Qué animal tiene una joroba?', a: ['camello', 'dromedario'] },
  { q: '¿Qué animal es símbolo de sabiduría?', a: ['buho', 'lechuza'] },
  { q: '¿Qué dinosaurio era famoso por sus brazos pequeños?', a: ['t rex', 'tiranosaurio rex'] },
  { q: '¿Qué animal blanco y negro come bambú?', a: ['panda', 'oso panda'] },

  // 🎬 Cine, series y anime
  { q: '¿Cómo se llama el martillo de Thor?', a: ['mjolnir'] },
  { q: '¿Cuál es el nombre real de Iron Man?', a: ['tony stark'] },
  { q: '¿Cuál es el nombre real de Spider-Man?', a: ['peter parker'] },
  { q: '¿Qué superhéroe usa un escudo con estrella?', a: ['capitan america'] },
  { q: '¿En qué saga aparece Darth Vader?', a: ['star wars'] },
  { q: '¿Qué personaje dice “Yo soy tu padre”?', a: ['darth vader'] },
  { q: '¿Qué princesa pierde una zapatilla de cristal?', a: ['cenicienta'] },
  { q: '¿Qué personaje vive en una piña debajo del mar?', a: ['bob esponja'] },
  { q: '¿Cómo se llama el amigo estrella de Bob Esponja?', a: ['patricio', 'patricio estrella'] },
  { q: '¿Qué anime tiene las esferas del dragón?', a: ['dragon ball'] },
  { q: '¿Cómo se llama el mejor amigo de Naruto?', a: ['sasuke'] },
  { q: '¿Cómo se llama el hermano de Sasuke?', a: ['itachi'] },
  { q: '¿Cómo se llama el capitán de los Piratas del Sombrero de Paja?', a: ['luffy', 'monkey d luffy'] },
  { q: '¿Qué personaje de anime quiere ser Hokage?', a: ['naruto'] },
  { q: '¿Qué anime tiene alquimistas y una piedra filosofal?', a: ['fullmetal alchemist'] },

  // 🎮 Videojuegos
  { q: '¿Cómo se llama el hermano de Mario?', a: ['luigi'] },
  { q: '¿Cómo se llama la princesa que Mario suele rescatar?', a: ['peach', 'princesa peach'] },
  { q: '¿Cómo se llama el villano tortuga de Mario?', a: ['bowser'] },
  { q: '¿Qué personaje usa espada y escudo en Zelda?', a: ['link'] },
  { q: '¿Cómo se llama la princesa de The Legend of Zelda?', a: ['zelda'] },
  { q: '¿Qué mineral azul es famoso en Minecraft?', a: ['diamante'] },
  { q: '¿Qué dimensión de Minecraft tiene al dragón final?', a: ['end', 'the end'] },
  { q: '¿Qué juego tiene agentes como Jett y Phoenix?', a: ['valorant'] },
  { q: '¿Qué juego tiene una ciudad llamada Los Santos?', a: ['gta v', 'gta 5', 'grand theft auto v'] },
  { q: '¿Qué juego tiene un personaje llamado Kratos?', a: ['god of war'] },
  { q: '¿Qué saga tiene asesinos y templarios?', a: ['assassins creed'] },
  { q: '¿Qué juego mezcla autos y fútbol?', a: ['rocket league'] },
  { q: '¿Qué juego tiene campeones y la Grieta del Invocador?', a: ['league of legends', 'lol'] },
  { q: '¿Qué juego tiene skins, bailes y pavos?', a: ['fortnite'] },
  { q: '¿Qué juego tiene una animatrónica llamada Freddy?', a: ['fnaf', 'five nights at freddys'] },

  // 🇵🇪 Perú
  { q: '¿Quién fue conocido como el Caballero de los Mares?', a: ['miguel grau', 'grau'] },
  { q: '¿Quién fue conocido como el Brujo de los Andes?', a: ['andres avelino caceres', 'caceres'] },
  { q: '¿Qué cultura construyó las Líneas de Nazca?', a: ['nazca', 'cultura nazca'] },
  { q: '¿En qué región está Machu Picchu?', a: ['cusco', 'cuzco'] },
  { q: '¿Qué río atraviesa la ciudad de Lima?', a: ['rimac', 'rio rimac'] },
  { q: '¿Qué plato peruano lleva papa, ají amarillo y queso?', a: ['papa a la huancaina', 'huancaina'] },
  { q: '¿Qué plato peruano mezcla arroz y pato?', a: ['arroz con pato'] },
  { q: '¿Qué danza peruana es típica de Puno?', a: ['diablada', 'diablada punena', 'diablada puneña'] },
  { q: '¿Qué escritor peruano ganó el Nobel de Literatura?', a: ['mario vargas llosa', 'vargas llosa'] },
  { q: '¿Cómo se llama la moneda actual del Perú?', a: ['sol', 'sol peruano'] },

  // 🤔 Lógica / trampitas
  { q: 'Si una docena son 12, ¿cuánto es media docena?', a: ['6', 'seis'] },
  { q: '¿Qué pesa más, un kilo de hierro o un kilo de algodón?', a: ['igual', 'pesan igual', 'lo mismo'] },
  { q: '¿Qué mes tiene 28 días?', a: ['febrero'] },
  { q: 'Si adelantas al segundo en una carrera, ¿en qué puesto quedas?', a: ['segundo', '2', '2do'] },
  { q: 'Si ayer fue lunes, ¿qué día es hoy?', a: ['martes'] },
  { q: 'Si hoy es viernes, ¿qué día será mañana?', a: ['sabado'] },
  { q: 'Si compras algo de 10 soles y pagas con 20, ¿cuánto vuelto recibes?', a: ['10', 'diez'] },
  { q: 'Si tienes 3 manzanas y te dan 2 más, ¿cuántas tienes?', a: ['5', 'cinco'] },
  { q: 'Si un tren sale a las 3 y tarda 2 horas, ¿a qué hora llega?', a: ['5', 'cinco', '5 pm', '17'] },
  { q: '¿Cuántos animales de cada especie llevó Moisés al arca?', a: ['ninguno', 'fue noe', 'noe'] },
  { q: '¿Capital de Croacia?', a: ['zagreb'] },
{ q: '¿Capital de Serbia?', a: ['belgrado'] },
{ q: '¿Capital de Eslovenia?', a: ['liubliana'] },
{ q: '¿Capital de Eslovaquia?', a: ['bratislava'] },
{ q: '¿Capital de Rumania?', a: ['bucarest'] },
{ q: '¿Capital de Bulgaria?', a: ['sofia'] },
{ q: '¿Capital de Ucrania?', a: ['kiev'] },
{ q: '¿Capital de Bielorrusia?', a: ['minsk'] },
{ q: '¿Capital de Lituania?', a: ['vilna'] },
{ q: '¿Capital de Letonia?', a: ['riga'] },
{ q: '¿Capital de Estonia?', a: ['tallin'] },
{ q: '¿Capital de Albania?', a: ['tirana'] },
{ q: '¿Capital de Macedonia del Norte?', a: ['skopie'] },
{ q: '¿Capital de Montenegro?', a: ['podgorica'] },
{ q: '¿Capital de Bosnia y Herzegovina?', a: ['sarajevo'] },
{ q: '¿Capital de Luxemburgo?', a: ['luxemburgo'] },
{ q: '¿Capital de Andorra?', a: ['andorra la vieja'] },
{ q: '¿Capital de Mónaco?', a: ['monaco'] },
{ q: '¿Capital de Liechtenstein?', a: ['vaduz'] },
{ q: '¿Capital de Malta?', a: ['la valeta'] },

{ q: '¿Qué planeta es conocido como el planeta azul?', a: ['tierra'] },
{ q: '¿Cuál es el planeta más caliente?', a: ['venus'] },
{ q: '¿Qué planeta tarda más en dar una vuelta al Sol?', a: ['neptuno'] },
{ q: '¿Qué planeta tiene más lunas conocidas?', a: ['saturno'] },
{ q: '¿Qué planeta tiene la gran mancha roja?', a: ['jupiter'] },

{ q: '¿Quién escribió Don Quijote?', a: ['miguel de cervantes', 'cervantes'] },
{ q: '¿Quién escribió La Odisea?', a: ['homero'] },
{ q: '¿Quién escribió Romeo y Julieta?', a: ['william shakespeare', 'shakespeare'] },
{ q: '¿Quién escribió El Principito?', a: ['antoine de saint exupery'] },
{ q: '¿Quién escribió Cien años de soledad?', a: ['gabriel garcia marquez'] },

{ q: '¿Cuál es el metal líquido a temperatura ambiente?', a: ['mercurio'] },
{ q: '¿Cuál es el elemento más abundante del universo?', a: ['hidrogeno'] },
{ q: '¿Cuál es el gas más abundante de la atmósfera?', a: ['nitrogeno'] },
{ q: '¿Qué órgano produce insulina?', a: ['pancreas'] },
{ q: '¿Qué órgano almacena la bilis?', a: ['vesicula'] },

{ q: '¿Cuántos dientes tiene normalmente un adulto?', a: ['32'] },
{ q: '¿Cuál es el hueso más pequeño del cuerpo?', a: ['estribo'] },
{ q: '¿Qué grupo sanguíneo es donante universal?', a: ['o negativo'] },
{ q: '¿Qué grupo sanguíneo es receptor universal?', a: ['ab positivo'] },
{ q: '¿Qué vitamina produce el cuerpo con la luz solar?', a: ['vitamina d'] },

{ q: '¿Cuál es el océano más pequeño?', a: ['artico'] },
{ q: '¿Cuál es el lago más grande del mundo?', a: ['mar caspio'] },
{ q: '¿Cuál es la isla más grande del mundo?', a: ['groenlandia'] },
{ q: '¿Cuál es el país más pequeño del mundo?', a: ['vaticano'] },
{ q: '¿Cuál es la ciudad más poblada de Japón?', a: ['tokio'] },

{ q: '¿Qué animal tiene tres corazones?', a: ['pulpo'] },
{ q: '¿Qué animal puede dormir de pie?', a: ['caballo'] },
{ q: '¿Qué ave puede imitar la voz humana?', a: ['loro'] },
{ q: '¿Qué mamífero puede volar?', a: ['murcielago'] },
{ q: '¿Qué animal tiene la mordida más fuerte?', a: ['cocodrilo'] },

{ q: '¿Qué videojuego tiene aldeanos y esmeraldas?', a: ['minecraft'] },
{ q: '¿Qué juego tiene personajes llamados Sage y Omen?', a: ['valorant'] },
{ q: '¿Qué juego tiene una tormenta que reduce el mapa?', a: ['fortnite'] },
{ q: '¿Qué juego tiene pokebolas?', a: ['pokemon'] },
{ q: '¿Qué juego tiene champiñones que hacen crecer a Mario?', a: ['super mario'] },

{ q: '¿Cuál es la velocidad aproximada de la luz?', a: ['300000 km/s', '300000'] },
{ q: '¿Qué científico formuló la teoría de la relatividad?', a: ['albert einstein', 'einstein'] },
{ q: '¿Quién descubrió la gravedad al observar una manzana?', a: ['isaac newton', 'newton'] },
{ q: '¿Quién descubrió la penicilina?', a: ['alexander fleming', 'fleming'] },
{ q: '¿Quién desarrolló las leyes del movimiento?', a: ['isaac newton', 'newton'] },

{ q: '¿Cuál es el idioma oficial de China?', a: ['mandarin'] },
{ q: '¿Cuál es el idioma oficial de Rusia?', a: ['ruso'] },
{ q: '¿Cuál es el idioma oficial de Turquía?', a: ['turco'] },
{ q: '¿Cuál es el idioma oficial de Holanda?', a: ['neerlandes'] },
{ q: '¿Cuál es el idioma oficial de Suecia?', a: ['sueco'] },

{ q: '¿Cuál es el símbolo químico del sodio?', a: ['na'] },
{ q: '¿Cuál es el símbolo químico del potasio?', a: ['k'] },
{ q: '¿Cuál es el símbolo químico del plomo?', a: ['pb'] },
{ q: '¿Cuál es el símbolo químico del estaño?', a: ['sn'] },
{ q: '¿Cuál es el símbolo químico del cobre?', a: ['cu'] },

{ q: '¿Cuántos jugadores tiene un equipo de béisbol?', a: ['9'] },
{ q: '¿Cuántos sets se necesitan para ganar un partido de tenis masculino en Grand Slam?', a: ['3'] },
{ q: '¿Qué deporte practica Novak Djokovic?', a: ['tenis'] },
{ q: '¿Qué deporte practica LeBron James?', a: ['baloncesto', 'basket'] },
{ q: '¿Qué deporte practica Max Verstappen?', a: ['formula 1'] },

{ q: '¿Cuál es el continente más frío?', a: ['antartida'] },
{ q: '¿Cuál es el mar más salado del mundo?', a: ['mar muerto'] },
{ q: '¿Cuál es el país con más habitantes de América?', a: ['estados unidos'] },
{ q: '¿Cuál es el río más largo de Sudamérica?', a: ['amazonas'] },
{ q: '¿Qué país tiene forma de largo y estrecho en Sudamérica?', a: ['chile'] },

{ q: '¿Quién fue el primer presidente de Estados Unidos?', a: ['george washington'] },
{ q: '¿Quién fue conocido como el Libertador de América?', a: ['simon bolivar'] },
{ q: '¿Quién lideró la independencia del Perú?', a: ['jose de san martin', 'san martin'] },
{ q: '¿Quién fue el último emperador inca?', a: ['atahualpa'] },
{ q: '¿Quién conquistó el Imperio Inca?', a: ['francisco pizarro', 'pizarro'] },
  { q: '¿Capital de Nepal?', a: ['katmandu'] },
{ q: '¿Capital de Pakistán?', a: ['islamabad'] },
{ q: '¿Capital de Afganistán?', a: ['kabul'] },
{ q: '¿Capital de Irak?', a: ['bagdad'] },
{ q: '¿Capital de Irán?', a: ['teheran'] },
{ q: '¿Capital de Siria?', a: ['damasco'] },
{ q: '¿Capital de Arabia Saudita?', a: ['riad'] },
{ q: '¿Capital de Emiratos Árabes Unidos?', a: ['abu dabi', 'abu dhabi'] },
{ q: '¿Capital de Catar?', a: ['doha'] },
{ q: '¿Capital de Kuwait?', a: ['kuwait'] },

{ q: '¿Qué planeta tiene un día más largo que su año?', a: ['venus'] },
{ q: '¿Cuál es la estrella más cercana a la Tierra después del Sol?', a: ['proxima centauri'] },
{ q: '¿Qué planeta fue degradado a planeta enano?', a: ['pluton'] },
{ q: '¿Qué planeta tiene color azul intenso por el metano?', a: ['neptuno'] },
{ q: '¿Qué planeta gira acostado sobre su eje?', a: ['urano'] },

{ q: '¿Quién compuso la Novena Sinfonía?', a: ['beethoven', 'ludwig van beethoven'] },
{ q: '¿Quién pintó La Última Cena?', a: ['leonardo da vinci', 'da vinci'] },
{ q: '¿Quién pintó Guernica?', a: ['pablo picasso', 'picasso'] },
{ q: '¿Quién pintó La noche estrellada?', a: ['vincent van gogh', 'van gogh'] },
{ q: '¿Quién esculpió David?', a: ['miguel angel', 'miguel angel buonarotti'] },

{ q: '¿Cuál es el idioma más hablado en Sudamérica?', a: ['espanol'] },
{ q: '¿Cuál es el idioma oficial de Austria?', a: ['aleman'] },
{ q: '¿Cuál es el idioma oficial de Hungría?', a: ['hungaro'] },
{ q: '¿Cuál es el idioma oficial de Polonia?', a: ['polaco'] },
{ q: '¿Cuál es el idioma oficial de Grecia?', a: ['griego'] },

{ q: '¿Qué instrumento mide los terremotos?', a: ['sismografo'] },
{ q: '¿Qué instrumento mide la presión atmosférica?', a: ['barometro'] },
{ q: '¿Qué instrumento mide la velocidad del viento?', a: ['anemometro'] },
{ q: '¿Qué instrumento orienta usando el norte magnético?', a: ['brujula'] },
{ q: '¿Qué instrumento amplía objetos lejanos?', a: ['telescopio'] },

{ q: '¿Qué animal puede regenerar partes de su cuerpo?', a: ['estrella de mar'] },
{ q: '¿Qué animal tiene la lengua más larga respecto a su cuerpo?', a: ['camaleon'] },
{ q: '¿Qué ave es símbolo de Estados Unidos?', a: ['aguila calva'] },
{ q: '¿Qué mamífero marino usa ecolocalización?', a: ['delfin'] },
{ q: '¿Qué pez es famoso por inflarse?', a: ['pez globo'] },

{ q: '¿Qué videojuego tiene una espada llamada Master Sword?', a: ['zelda', 'the legend of zelda'] },
{ q: '¿Qué juego tiene bloques de redstone?', a: ['minecraft'] },
{ q: '¿Qué juego tiene agentes como Reyna y Cypher?', a: ['valorant'] },
{ q: '¿Qué juego tiene una tormenta llamada Niebla?', a: ['free fire'] },
{ q: '¿Qué juego tiene personajes llamados Ash y Mirage?', a: ['apex legends'] },

{ q: '¿Cuál es la capital de Kenia?', a: ['nairobi'] },
{ q: '¿Cuál es la capital de Etiopía?', a: ['adis abeba'] },
{ q: '¿Cuál es la capital de Sudáfrica administrativa?', a: ['pretoria'] },
{ q: '¿Cuál es la capital de Nigeria?', a: ['abuya', 'abuja'] },
{ q: '¿Cuál es la capital de Ghana?', a: ['acra'] },

{ q: '¿Qué científico propuso la evolución por selección natural?', a: ['charles darwin', 'darwin'] },
{ q: '¿Quién desarrolló la tabla periódica?', a: ['dmitri mendeleiev', 'mendeleiev'] },
{ q: '¿Quién descubrió la radiactividad?', a: ['henri becquerel'] },
{ q: '¿Quién descubrió el electrón?', a: ['j j thomson', 'thomson'] },
{ q: '¿Quién descubrió América para Europa?', a: ['cristobal colon'] },

{ q: '¿Cuánto es 17 x 6?', a: ['102'] },
{ q: '¿Cuánto es 19 x 4?', a: ['76'] },
{ q: '¿Cuánto es 144 dividido entre 12?', a: ['12'] },
{ q: '¿Cuál es la raíz cuadrada de 169?', a: ['13'] },
{ q: '¿Cuál es la raíz cuadrada de 225?', a: ['15'] },

{ q: '¿Qué país ganó el Mundial 2018?', a: ['francia'] },
{ q: '¿Qué país ganó el Mundial 2014?', a: ['alemania'] },
{ q: '¿Qué país ganó el Mundial 2010?', a: ['espana'] },
{ q: '¿Qué país ganó el Mundial 2006?', a: ['italia'] },
{ q: '¿Qué país ganó el Mundial 2002?', a: ['brasil'] },

{ q: '¿Qué red social fue creada por Elon Musk tras comprar Twitter?', a: ['x'] },
{ q: '¿Qué empresa desarrolla ChatGPT?', a: ['openai'] },
{ q: '¿Qué empresa creó Windows?', a: ['microsoft'] },
{ q: '¿Qué empresa creó Chrome?', a: ['google'] },
{ q: '¿Qué empresa creó Instagram?', a: ['meta', 'facebook'] },

{ q: '¿Qué continente tiene más países?', a: ['africa'] },
{ q: '¿Qué país tiene la Torre de Pisa?', a: ['italia'] },
{ q: '¿Qué país tiene el Cristo Redentor?', a: ['brasil'] },
{ q: '¿Qué país tiene el Big Ben?', a: ['reino unido'] },
{ q: '¿Qué país tiene la Estatua de la Libertad?', a: ['estados unidos'] },

{ q: '¿Qué personaje usa un martillo llamado Stormbreaker?', a: ['thor'] },
{ q: '¿Cómo se llama el hermano de Thor?', a: ['loki'] },
{ q: '¿Qué héroe se transforma al decir Shazam?', a: ['shazam'] },
{ q: '¿Qué héroe usa un anillo de poder verde?', a: ['linterna verde'] },
{ q: '¿Qué héroe tiene garras de adamantium?', a: ['wolverine'] },

{ q: '¿Qué dinosaurio tenía tres cuernos?', a: ['triceratops'] },
{ q: '¿Qué dinosaurio tenía placas en la espalda?', a: ['estegosaurio'] },
{ q: '¿Qué dinosaurio volador famoso aparece en libros?', a: ['pterodactilo'] },
{ q: '¿Qué dinosaurio era herbívoro de cuello largo?', a: ['braquiosaurio'] },
{ q: '¿Qué dinosaurio era conocido como T-Rex?', a: ['tiranosaurio rex'] },

{ q: '¿Qué océano baña la costa occidental de América?', a: ['pacifico'] },
{ q: '¿Qué océano baña la costa oriental de América?', a: ['atlantico'] },
{ q: '¿Qué mar separa Europa y África?', a: ['mediterraneo'] },
{ q: '¿Qué estrecho separa Asia y América?', a: ['bering'] },
{ q: '¿Qué canal conecta el Mediterráneo con el Mar Rojo?', a: ['canal de suez'] },

{ q: '¿Qué fruta tiene semillas por fuera?', a: ['fresa'] },
{ q: '¿Qué fruta tropical tiene corona de hojas?', a: ['pina', 'piña'] },
{ q: '¿Qué fruta es conocida como king of fruits en Asia?', a: ['durian'] },
{ q: '¿Qué fruto seco produce el nogal?', a: ['nuez'] },
{ q: '¿Qué fruta cítrica es de color naranja?', a: ['naranja'] }
  ];

preguntas.push(
/* 🌍 GEOGRAFÍA */

{ q: '¿Capital de Croacia?', a: ['zagreb'] },
{ q: '¿Capital de Serbia?', a: ['belgrado'] },
{ q: '¿Capital de Eslovaquia?', a: ['bratislava'] },
{ q: '¿Capital de Eslovenia?', a: ['liubliana', 'ljubljana'] },
{ q: '¿Capital de Rumanía?', a: ['bucarest'] },
{ q: '¿Capital de Bulgaria?', a: ['sofia'] },
{ q: '¿Capital de Ucrania?', a: ['kiev', 'kyiv'] },
{ q: '¿Capital de Bielorrusia?', a: ['minsk'] },
{ q: '¿Capital de Lituania?', a: ['vilna', 'vilnius'] },
{ q: '¿Capital de Letonia?', a: ['riga'] },
{ q: '¿Capital de Estonia?', a: ['tallin', 'tallinn'] },
{ q: '¿Capital de Albania?', a: ['tirana'] },
{ q: '¿Capital de Macedonia del Norte?', a: ['skopie', 'skopje'] },
{ q: '¿Capital de Montenegro?', a: ['podgorica'] },
{ q: '¿Capital de Luxemburgo?', a: ['luxemburgo'] },

/* 🧪 CIENCIA */

{ q: '¿Planeta conocido como el gigante gaseoso?', a: ['jupiter'] },
{ q: '¿Planeta inclinado casi de lado?', a: ['urano'] },
{ q: '¿Planeta más lejano del Sol?', a: ['neptuno'] },
{ q: '¿Qué órgano produce insulina?', a: ['pancreas'] },
{ q: '¿Cuál es el hueso más pequeño del cuerpo?', a: ['estribo'] },
{ q: '¿Qué órgano controla el equilibrio?', a: ['cerebelo'] },
{ q: '¿Qué vitamina produce el cuerpo con el Sol?', a: ['vitamina d'] },
{ q: '¿Qué metal es líquido a temperatura ambiente?', a: ['mercurio'] },
{ q: '¿Cuál es el metal más ligero?', a: ['litio'] },
{ q: '¿Cuál es el elemento más abundante del universo?', a: ['hidrogeno'] },
{ q: '¿Qué gas utilizan los globos aerostáticos modernos?', a: ['helio'] },
{ q: '¿Qué órgano humano tiene cuatro cavidades?', a: ['corazon'] },
{ q: '¿Cuál es el único mamífero capaz de volar?', a: ['murcielago'] },
{ q: '¿Qué tipo de sangre es donante universal?', a: ['o negativo'] },
{ q: '¿Qué tipo de sangre es receptor universal?', a: ['ab positivo'] },

/* 🦖 ANIMALES */

{ q: '¿Animal más rápido en el agua?', a: ['pez vela'] },
{ q: '¿Ave símbolo de Estados Unidos?', a: ['aguila calva'] },
{ q: '¿Qué animal tiene ocho patas?', a: ['arana'] },
{ q: '¿Animal conocido por su bolsa marsupial?', a: ['canguro'] },
{ q: '¿Animal que puede girar su cabeza casi 270 grados?', a: ['buho'] },
{ q: '¿Animal más venenoso del mundo?', a: ['medusa caja'] },
{ q: '¿Qué animal tiene manchas y corre velozmente?', a: ['guepardo'] },
{ q: '¿Qué animal construye colmenas?', a: ['abeja'] },
{ q: '¿Animal marino conocido por cantar?', a: ['ballena'] },
{ q: '¿Qué animal es llamado el mejor amigo del hombre?', a: ['perro'] },
{ q: '¿Animal que produce seda?', a: ['gusano de seda'] },
{ q: '¿Animal con pico y cola plana?', a: ['ornitorrinco'] },
{ q: '¿Animal símbolo de la paz?', a: ['paloma'] },
{ q: '¿Qué animal tiene una melena?', a: ['leon'] },
{ q: '¿Animal más grande de África?', a: ['elefante'] },

/* ⚽ DEPORTES */

{ q: '¿Cuántos sets se necesitan para ganar en tenis masculino Grand Slam?', a: ['3'] },
{ q: '¿Deporte donde se usa una red y una pelota liviana?', a: ['voleibol'] },
{ q: '¿País de origen del judo?', a: ['japon'] },
{ q: '¿País de origen del taekwondo?', a: ['corea del sur'] },
{ q: '¿Deporte donde se usa un puck?', a: ['hockey sobre hielo'] },
{ q: '¿Cuántos jugadores hay en un equipo de baloncesto en cancha?', a: ['5'] },
{ q: '¿Deporte practicado por Tiger Woods?', a: ['golf'] },
{ q: '¿Deporte donde compite Simone Biles?', a: ['gimnasia'] },
{ q: '¿País que inventó el fútbol moderno?', a: ['inglaterra'] },
{ q: '¿Cuántos anillos olímpicos existen?', a: ['5'] },
{ q: '¿Color de la camiseta tradicional de Argentina?', a: ['celeste y blanco'] },
{ q: '¿Cuánto dura un partido de fútbol reglamentario?', a: ['90 minutos'] },
{ q: '¿Cuántos hoyos tiene un recorrido estándar de golf?', a: ['18'] },
{ q: '¿Deporte donde se usa una tabla y olas?', a: ['surf'] },
{ q: '¿País de origen del sumo?', a: ['japon'] },

/* 🎮 VIDEOJUEGOS */

{ q: '¿Compañía creadora de Pokémon?', a: ['nintendo'] },
{ q: '¿Nombre del protagonista de The Legend of Zelda?', a: ['link'] },
{ q: '¿Personaje principal de Metal Gear Solid?', a: ['solid snake'] },
{ q: '¿Mascota de Sega?', a: ['sonic'] },
{ q: '¿Personaje principal de Tomb Raider?', a: ['lara croft'] },
{ q: '¿Videojuego donde aparecen Spartans?', a: ['halo'] },
{ q: '¿Empresa creadora de GTA?', a: ['rockstar games'] },
{ q: '¿Juego donde aparece Geralt de Rivia?', a: ['the witcher'] },
{ q: '¿Personaje principal de God of War?', a: ['kratos'] },
{ q: '¿Juego famoso por bloques y minería?', a: ['minecraft'] },
{ q: '¿Videojuego protagonizado por Samus Aran?', a: ['metroid'] },
{ q: '¿Juego donde aparece Cloud Strife?', a: ['final fantasy vii'] },
{ q: '¿Compañía creadora de Fortnite?', a: ['epic games'] },
{ q: '¿Videojuego protagonizado por Arthur Morgan?', a: ['red dead redemption 2'] },
{ q: '¿Saga de videojuegos con asesinos ocultos?', a: ['assassins creed'] },

/* 🎬 CINE */

{ q: '¿Actor que interpretó a Iron Man?', a: ['robert downey jr'] },
{ q: '¿Actor que interpretó a Wolverine?', a: ['hugh jackman'] },
{ q: '¿Director de Titanic?', a: ['james cameron'] },
{ q: '¿Director de Jurassic Park?', a: ['steven spielberg'] },
{ q: '¿Nombre del hobbit protagonista de El Señor de los Anillos?', a: ['frodo'] },
{ q: '¿Nombre del mago gris de El Señor de los Anillos?', a: ['gandalf'] },
{ q: '¿Quién interpreta a Jack Sparrow?', a: ['johnny depp'] },
{ q: '¿Película donde aparece el personaje Neo?', a: ['matrix'] },
{ q: '¿Nombre del león villano en El Rey León?', a: ['scar'] },
{ q: '¿Princesa protagonista de Enredados?', a: ['rapunzel'] },
{ q: '¿Princesa protagonista de La Sirenita?', a: ['ariel'] },
{ q: '¿Nombre del robot protagonista de Wall-E?', a: ['wall e'] },
{ q: '¿Personaje principal de Gladiador?', a: ['maximo'] },
{ q: '¿Actor que interpretó a Harry Potter?', a: ['daniel radcliffe'] },
{ q: '¿Director de Avatar?', a: ['james cameron'] },

/* 📚 LITERATURA */

{ q: '¿Autor de Don Quijote de la Mancha?', a: ['miguel de cervantes'] },
{ q: '¿Autor de Romeo y Julieta?', a: ['william shakespeare'] },
{ q: '¿Autor de La Odisea?', a: ['homero'] },
{ q: '¿Autor de El Principito?', a: ['antoine de saint exupery'] },
{ q: '¿Autor de 1984?', a: ['george orwell'] },
{ q: '¿Autor de El Hobbit?', a: ['jrr tolkien', 'tolkien'] },
{ q: '¿Autor de Moby Dick?', a: ['herman melville'] },
{ q: '¿Autor de Drácula?', a: ['bram stoker'] },
{ q: '¿Autor de Frankenstein?', a: ['mary shelley'] },
{ q: '¿Autor de La Divina Comedia?', a: ['dante alighieri'] },

/* 🎵 MÚSICA */

{ q: '¿Compositor de La Quinta Sinfonía?', a: ['beethoven'] },
{ q: '¿Compositor de Las Cuatro Estaciones?', a: ['vivaldi'] },
{ q: '¿Compositor de El Lago de los Cisnes?', a: ['tchaikovsky'] },
{ q: '¿Instrumento principal de Mozart?', a: ['piano'] },
{ q: '¿Grupo de Freddie Mercury?', a: ['queen'] },
{ q: '¿Cantante conocido como Rey del Rock?', a: ['elvis presley'] },
{ q: '¿Cantante de Shape of You?', a: ['ed sheeran'] },
{ q: '¿Cantante de Bad Romance?', a: ['lady gaga'] },
{ q: '¿Grupo británico formado por Lennon y McCartney?', a: ['the beatles'] },
{ q: '¿Instrumento típico del mariachi?', a: ['trompeta'] },

/* 💻 TECNOLOGÍA */

{ q: '¿Qué significa CPU?', a: ['unidad central de procesamiento'] },
{ q: '¿Qué significa RAM?', a: ['memoria de acceso aleatorio'] },
{ q: '¿Qué empresa desarrolla Windows?', a: ['microsoft'] },
{ q: '¿Qué empresa desarrolla macOS?', a: ['apple'] },
{ q: '¿Lenguaje usado para páginas web junto a HTML?', a: ['css'] },
{ q: '¿Lenguaje de programación creado por Guido van Rossum?', a: ['python'] },
{ q: '¿Qué empresa creó YouTube?', a: ['google'] },
{ q: '¿Quién fundó SpaceX?', a: ['elon musk'] },
{ q: '¿Sistema operativo basado en Linux para móviles?', a: ['android'] },
{ q: '¿Navegador desarrollado por Microsoft?', a: ['edge'] },

/* 🤔 LÓGICA */

{ q: '¿Qué mes tiene menos días?', a: ['febrero'] },
{ q: '¿Cuántas patas tienen dos arañas?', a: ['16'] },
{ q: '¿Cuánto es una docena más una docena?', a: ['24'] },
{ q: '¿Cuántas ruedas tienen tres bicicletas?', a: ['6'] },
{ q: '¿Cuántos lados tienen dos triángulos?', a: ['6'] },
{ q: '¿Qué número viene después del 999?', a: ['1000'] },
{ q: '¿Qué número está entre 49 y 51?', a: ['50'] },
{ q: '¿Cuánto es un lustro?', a: ['5 anos', '5 años'] },
{ q: '¿Cuántos años tiene una década?', a: ['10'] },
{ q: '¿Cuántos años tiene un siglo?', a: ['100'] }, 
  { q: '¿Cuál es el océano más frío?', a: ['artico', 'oceano artico'] },
{ q: '¿Cuál es el continente más poblado?', a: ['asia'] },
{ q: '¿Cuál es el país más pequeño del mundo?', a: ['vaticano', 'ciudad del vaticano'] },
{ q: '¿Cuál es la capital de Nueva Zelanda?', a: ['wellington'] },
{ q: '¿Cuál es la capital de Sudáfrica administrativa?', a: ['pretoria'] },
{ q: '¿Cuál es la capital de Croacia?', a: ['zagreb'] },
{ q: '¿Cuál es la capital de Serbia?', a: ['belgrado'] },
{ q: '¿Cuál es la capital de Ucrania?', a: ['kiev', 'kyiv'] },
{ q: '¿Cuál es la capital de Rumania?', a: ['bucarest'] },
{ q: '¿Cuál es la capital de Bulgaria?', a: ['sofia'] },

{ q: '¿Cuál es el planeta más caliente?', a: ['venus'] },
{ q: '¿Cuál es el planeta más lejano al Sol?', a: ['neptuno'] },
{ q: '¿Cuál es el cuarto planeta del sistema solar?', a: ['marte'] },
{ q: '¿Cuál es el séptimo planeta del sistema solar?', a: ['urano'] },
{ q: '¿Qué planeta gira acostado?', a: ['urano'] },
{ q: '¿Cómo se llama nuestra estrella?', a: ['sol'] },
{ q: '¿Qué planeta tiene la Gran Mancha Roja?', a: ['jupiter'] },
{ q: '¿Cuál es el satélite más grande de Saturno?', a: ['titan'] },
{ q: '¿Cómo se llama la galaxia vecina más famosa?', a: ['andromeda'] },
{ q: '¿Qué estudia la astronomía?', a: ['astros', 'universo'] },

{ q: '¿Qué vitamina produce el cuerpo con el Sol?', a: ['vitamina d'] },
{ q: '¿Cuál es el órgano más grande del cuerpo humano?', a: ['piel'] },
{ q: '¿Qué órgano produce la bilis?', a: ['higado'] },
{ q: '¿Qué órgano almacena la bilis?', a: ['vesicula'] },
{ q: '¿Cuántos dientes tiene un adulto normalmente?', a: ['32'] },
{ q: '¿Qué parte del ojo da color?', a: ['iris'] },
{ q: '¿Qué líquido bombea el corazón?', a: ['sangre'] },
{ q: '¿Qué órgano controla el equilibrio?', a: ['cerebelo'] },
{ q: '¿Qué órgano humano tiene cuatro cavidades?', a: ['corazon'] },
{ q: '¿Dónde se encuentran las cuerdas vocales?', a: ['laringe'] },

{ q: '¿Qué animal es conocido como el mejor amigo del hombre?', a: ['perro'] },
{ q: '¿Qué animal puede vivir muchos años en el desierto?', a: ['camello'] },
{ q: '¿Qué ave puede girar mucho su cabeza?', a: ['buho'] },
{ q: '¿Qué pez es famoso por su memoria corta?', a: ['pez dorado'] },
{ q: '¿Qué mamífero marino usa ecolocalización?', a: ['delfin'] },
{ q: '¿Qué animal tiene púas para defenderse?', a: ['puercoespin'] },
{ q: '¿Qué animal construye panales?', a: ['abeja'] },
{ q: '¿Qué ave simboliza la paz?', a: ['paloma'] },
{ q: '¿Qué felino es el más grande del mundo?', a: ['tigre'] },
{ q: '¿Qué animal es famoso por su lentitud?', a: ['perezoso'] },

{ q: '¿Qué instrumento tiene teclas y pedales?', a: ['piano'] },
{ q: '¿Qué instrumento se toca soplando y tiene pistones?', a: ['trompeta'] },
{ q: '¿Qué instrumento tiene cuatro cuerdas y arco?', a: ['violin'] },
{ q: '¿Qué instrumento es típico del mariachi?', a: ['guitarra'] },
{ q: '¿Qué cantante era conocido como El Rey?', a: ['vicente fernandez'] },
{ q: '¿Quién cantaba Bohemian Rhapsody?', a: ['queen'] },
{ q: '¿Qué banda cantaba Yesterday?', a: ['beatles'] },
{ q: '¿Qué género musical nació en Jamaica?', a: ['reggae'] },
{ q: '¿Qué cantante es conocida como La Reina del Tex-Mex?', a: ['selena'] },
{ q: '¿Qué aplicación pertenece a Meta además de Facebook?', a: ['instagram'] },

{ q: '¿Qué consola lanzó Nintendo en 2006?', a: ['wii'] },
{ q: '¿Qué consola lanzó Sony en 1994?', a: ['playstation'] },
{ q: '¿Quién es el protagonista de The Legend of Zelda?', a: ['link'] },
{ q: '¿Qué personaje amarillo recoge monedas en laberintos?', a: ['pacman'] },
{ q: '¿Qué personaje usa gorra roja y bigote?', a: ['mario'] },
{ q: '¿Qué juego tiene bloques llamados obsidiana?', a: ['minecraft'] },
{ q: '¿Qué juego tiene una isla llamada Verdansk?', a: ['warzone'] },
{ q: '¿Qué empresa creó Pokémon?', a: ['nintendo'] },
{ q: '¿Qué juego tiene aldeanos y creepers?', a: ['minecraft'] },
{ q: '¿Qué juego tiene impostores y tripulantes?', a: ['among us'] },

{ q: '¿Quién escribió Don Quijote?', a: ['miguel de cervantes', 'cervantes'] },
{ q: '¿Quién escribió Romeo y Julieta?', a: ['william shakespeare', 'shakespeare'] },
{ q: '¿Quién escribió La Odisea?', a: ['homero'] },
{ q: '¿Quién escribió La Ilíada?', a: ['homero'] },
{ q: '¿Quién escribió El Principito?', a: ['antoine de saint exupery'] },
{ q: '¿Quién escribió Cien años de soledad?', a: ['gabriel garcia marquez'] },
{ q: '¿Quién escribió La Metamorfosis?', a: ['franz kafka'] },
{ q: '¿Qué escritor creó Sherlock Holmes?', a: ['arthur conan doyle'] },
{ q: '¿Qué escritor creó Drácula?', a: ['bram stoker'] },
{ q: '¿Qué escritor creó Frankenstein?', a: ['mary shelley'] },

{ q: '¿Cuál es el resultado de 17 x 6?', a: ['102'] },
{ q: '¿Cuál es el resultado de 25 x 8?', a: ['200'] },
{ q: '¿Cuál es el resultado de 144 / 12?', a: ['12'] },
{ q: '¿Cuál es el resultado de 81 + 19?', a: ['100'] },
{ q: '¿Cuál es el resultado de 250 - 75?', a: ['175'] },
{ q: '¿Cuál es el resultado de 14 x 14?', a: ['196'] },
{ q: '¿Cuál es el resultado de 30 x 30?', a: ['900'] },
{ q: '¿Cuál es el resultado de 500 / 5?', a: ['100'] },
{ q: '¿Cuál es el resultado de 7 x 13?', a: ['91'] },
{ q: '¿Cuál es el resultado de 90 - 45?', a: ['45'] },

{ q: '¿Qué color resulta de mezclar rojo y azul?', a: ['morado', 'violeta'] },
{ q: '¿Qué color resulta de mezclar azul y amarillo?', a: ['verde'] },
{ q: '¿Qué color resulta de mezclar rojo y amarillo?', a: ['naranja'] },
{ q: '¿Cuál es el color del carbón?', a: ['negro'] },
{ q: '¿Cuál es el color asociado a la esperanza?', a: ['verde'] },
{ q: '¿Cuál es el color asociado al amor?', a: ['rojo'] },
{ q: '¿Cuál es el color asociado a la realeza?', a: ['morado'] },
{ q: '¿Cuál es el color de las esmeraldas?', a: ['verde'] },
{ q: '¿Cuál es el color de los zafiros?', a: ['azul'] },
{ q: '¿Cuál es el color de los rubíes?', a: ['rojo'] },

{ q: '¿Qué país tiene forma de hexágono en Europa?', a: ['francia'] },
{ q: '¿Qué ciudad es conocida como la Gran Manzana?', a: ['nueva york'] },
{ q: '¿Qué ciudad es conocida como la Ciudad Luz?', a: ['paris'] },
{ q: '¿Qué ciudad es famosa por el Big Ben?', a: ['londres'] },
{ q: '¿Qué ciudad alberga el Coliseo?', a: ['roma'] },
{ q: '¿Qué ciudad alberga la Estatua de la Libertad?', a: ['nueva york'] },
{ q: '¿Qué ciudad alberga la Ópera de Sídney?', a: ['sidney'] },
{ q: '¿Qué ciudad es capital de Cataluña?', a: ['barcelona'] },
{ q: '¿Qué ciudad está atravesada por el río Sena?', a: ['paris'] },
{ q: '¿Qué ciudad es famosa por sus canales?', a: ['venecia'] },

{ q: '¿Qué personaje vive en Fondo de Bikini?', a: ['bob esponja'] },
{ q: '¿Qué personaje es amigo de Bob Esponja y vive bajo una roca?', a: ['patricio'] },
{ q: '¿Qué personaje tiene una casa en forma de piña?', a: ['bob esponja'] },
{ q: '¿Qué personaje de Disney tiene una lámpara mágica?', a: ['aladdin'] },
{ q: '¿Qué personaje pierde un zapato de cristal?', a: ['cenicienta'] },
{ q: '¿Qué personaje tiene una larga cabellera mágica?', a: ['rapunzel'] },
{ q: '¿Qué personaje tiene una nariz que crece al mentir?', a: ['pinocho'] },
{ q: '¿Qué personaje vive en Nunca Jamás?', a: ['peter pan'] },
{ q: '¿Qué personaje tiene siete enanitos como amigos?', a: ['blancanieves'] },
{ q: '¿Qué personaje es una sirena de Disney?', a: ['ariel'] }, 
  { q: '¿Cuál es la capital de Eslovaquia?', a: ['bratislava'] },
{ q: '¿Cuál es la capital de Eslovenia?', a: ['liubliana', 'ljubljana'] },
{ q: '¿Cuál es la capital de Letonia?', a: ['riga'] },
{ q: '¿Cuál es la capital de Lituania?', a: ['vilna', 'vilnius'] },
{ q: '¿Cuál es la capital de Estonia?', a: ['tallin', 'tallinn'] },
{ q: '¿Cuál es la capital de Bielorrusia?', a: ['minsk'] },
{ q: '¿Cuál es la capital de Kazajistán?', a: ['astana'] },
{ q: '¿Cuál es la capital de Mongolia?', a: ['ulaanbaatar'] },
{ q: '¿Cuál es la capital de Pakistán?', a: ['islamabad'] },
{ q: '¿Cuál es la capital de Indonesia?', a: ['yakarta', 'jakarta'] },

{ q: '¿Qué planeta es conocido como el planeta azul?', a: ['tierra'] },
{ q: '¿Qué planeta tiene más lunas conocidas?', a: ['saturno'] },
{ q: '¿Cuál es la estrella más cercana a la Tierra?', a: ['sol'] },
{ q: '¿Cómo se llama el satélite natural de Marte más grande?', a: ['fobos'] },
{ q: '¿Cuál es el planeta más pequeño del sistema solar?', a: ['mercurio'] },
{ q: '¿Qué fenómeno ocurre cuando la Luna tapa al Sol?', a: ['eclipse solar'] },
{ q: '¿Qué fenómeno ocurre cuando la Tierra tapa la Luna?', a: ['eclipse lunar'] },
{ q: '¿Qué instrumento mide terremotos?', a: ['sismografo'] },
{ q: '¿Qué ciencia estudia los volcanes?', a: ['vulcanologia'] },
{ q: '¿Qué ciencia estudia los fósiles?', a: ['paleontologia'] },

{ q: '¿Cuál es el metal líquido a temperatura ambiente?', a: ['mercurio'] },
{ q: '¿Qué gas usan los globos para flotar?', a: ['helio'] },
{ q: '¿Qué órgano produce insulina?', a: ['pancreas'] },
{ q: '¿Qué órgano almacena la orina?', a: ['vejiga'] },
{ q: '¿Cuál es el músculo más fuerte del cuerpo por tamaño?', a: ['masetero'] },
{ q: '¿Qué parte del cuerpo contiene el esmalte?', a: ['dientes'] },
{ q: '¿Cuál es el hueso más pequeño del cuerpo?', a: ['estribo'] },
{ q: '¿Qué vitamina se asocia con las zanahorias?', a: ['vitamina a'] },
{ q: '¿Qué enfermedad causa falta de vitamina C?', a: ['escorbuto'] },
{ q: '¿Qué líquido transporta oxígeno por el cuerpo?', a: ['sangre'] },

{ q: '¿Qué animal puede dormir de pie?', a: ['caballo'] },
{ q: '¿Qué animal tiene manchas y cuello largo?', a: ['jirafa'] },
{ q: '¿Qué animal vive en madrigueras y salta?', a: ['conejo'] },
{ q: '¿Qué animal es símbolo de Canadá?', a: ['castor'] },
{ q: '¿Qué animal es conocido por construir diques?', a: ['castor'] },
{ q: '¿Qué animal tiene ocho patas y produce seda?', a: ['arana'] },
{ q: '¿Qué animal es famoso por imitar sonidos humanos?', a: ['loro'] },
{ q: '¿Qué animal vive en el Ártico y es blanco?', a: ['oso polar'] },
{ q: '¿Qué animal marino tiene caparazón y pinzas?', a: ['langosta'] },
{ q: '¿Qué animal puede inflarse para defenderse?', a: ['pez globo'] },

{ q: '¿Quién compuso La Quinta Sinfonía?', a: ['beethoven'] },
{ q: '¿Quién compuso Las Cuatro Estaciones?', a: ['vivaldi'] },
{ q: '¿Quién compuso El Lago de los Cisnes?', a: ['tchaikovsky'] },
{ q: '¿Qué instrumento tiene teclas blancas y negras?', a: ['piano'] },
{ q: '¿Qué instrumento suele tener 88 teclas?', a: ['piano'] },
{ q: '¿Qué género musical nació en Nueva Orleans?', a: ['jazz'] },
{ q: '¿Qué género musical nació en Estados Unidos y usa rimas?', a: ['rap'] },
{ q: '¿Qué cantante era líder de Queen?', a: ['freddie mercury'] },
{ q: '¿Qué banda cantó Hotel California?', a: ['eagles'] },
{ q: '¿Qué banda británica tuvo a Mick Jagger?', a: ['rolling stones'] },

{ q: '¿Qué empresa creó la consola GameCube?', a: ['nintendo'] },
{ q: '¿Qué empresa creó la consola Dreamcast?', a: ['sega'] },
{ q: '¿Qué mascota tiene Sega?', a: ['sonic'] },
{ q: '¿Qué personaje usa una espada maestra?', a: ['link'] },
{ q: '¿Qué personaje secuestra a la princesa Peach?', a: ['bowser'] },
{ q: '¿Qué enemigo de Mario tiene caparazón?', a: ['koopa'] },
{ q: '¿Qué juego tiene bloques de redstone?', a: ['minecraft'] },
{ q: '¿Qué juego tiene personajes llamados creepers y enderman?', a: ['minecraft'] },
{ q: '¿Qué juego tiene un autobús de batalla?', a: ['fortnite'] },
{ q: '¿Qué juego tiene mapas llamados Dust2 y Mirage?', a: ['counter strike'] },

{ q: '¿Quién escribió La Divina Comedia?', a: ['dante alighieri'] },
{ q: '¿Quién escribió Hamlet?', a: ['william shakespeare'] },
{ q: '¿Quién escribió Los Miserables?', a: ['victor hugo'] },
{ q: '¿Quién escribió El Conde de Montecristo?', a: ['alexandre dumas'] },
{ q: '¿Quién escribió Veinte mil leguas de viaje submarino?', a: ['julio verne'] },
{ q: '¿Quién escribió La vuelta al mundo en 80 días?', a: ['julio verne'] },
{ q: '¿Quién escribió El viejo y el mar?', a: ['ernest hemingway'] },
{ q: '¿Quién escribió Orgullo y prejuicio?', a: ['jane austen'] },
{ q: '¿Quién escribió Moby Dick?', a: ['herman melville'] },
{ q: '¿Quién escribió Alicia en el país de las maravillas?', a: ['lewis carroll'] },

{ q: '¿Cuánto es 16 x 16?', a: ['256'] },
{ q: '¿Cuánto es 18 x 18?', a: ['324'] },
{ q: '¿Cuánto es 22 x 5?', a: ['110'] },
{ q: '¿Cuánto es 75 + 25?', a: ['100'] },
{ q: '¿Cuánto es 400 / 8?', a: ['50'] },
{ q: '¿Cuánto es 11 x 11?', a: ['121'] },
{ q: '¿Cuánto es 13 x 13?', a: ['169'] },
{ q: '¿Cuánto es 144 + 56?', a: ['200'] },
{ q: '¿Cuánto es 1000 - 250?', a: ['750'] },
{ q: '¿Cuánto es 120 / 3?', a: ['40'] },

{ q: '¿Qué ciudad es conocida como la Ciudad Eterna?', a: ['roma'] },
{ q: '¿Qué ciudad alberga la Torre Inclinada?', a: ['pisa'] },
{ q: '¿Qué ciudad es famosa por la Sagrada Familia?', a: ['barcelona'] },
{ q: '¿Qué ciudad es famosa por el Kremlin?', a: ['moscu'] },
{ q: '¿Qué ciudad es famosa por la Puerta de Brandeburgo?', a: ['berlin'] },
{ q: '¿Qué ciudad es famosa por el Cristo Redentor?', a: ['rio de janeiro'] },
{ q: '¿Qué ciudad es famosa por Times Square?', a: ['nueva york'] },
{ q: '¿Qué ciudad es famosa por la Ópera Garnier?', a: ['paris'] },
{ q: '¿Qué ciudad es famosa por el Golden Gate?', a: ['san francisco'] },
{ q: '¿Qué ciudad es famosa por la Acrópolis?', a: ['atenas'] },

{ q: '¿Qué princesa tiene un amigo llamado Sebastián?', a: ['ariel'] },
{ q: '¿Qué personaje tiene un genio azul?', a: ['aladdin'] },
{ q: '¿Qué personaje vive en una lámpara mágica?', a: ['genio'] },
{ q: '¿Qué personaje tiene un tigre llamado Rajah?', a: ['jasmine'] },
{ q: '¿Qué personaje de Disney duerme cien años?', a: ['aurora'] },
{ q: '¿Qué personaje tiene una rosa encantada?', a: ['bella'] },
{ q: '¿Qué personaje es una muñeca vaquera en Toy Story?', a: ['jessie'] },
{ q: '¿Qué personaje es un astronauta de Toy Story?', a: ['buzz lightyear'] },
{ q: '¿Qué personaje vive en una casa de hongos?', a: ['pitufos'] },
{ q: '¿Qué personaje amarillo usa pantalones cuadrados?', a: ['bob esponja'] }, 
  { q: '¿Qué Pokémon es la evolución de Bulbasaur?', a: ['ivysaur'] },
{ q: '¿Qué Pokémon es la evolución de Ivysaur?', a: ['venusaur'] },
{ q: '¿Qué Pokémon es la evolución de Charmander?', a: ['charmeleon'] },
{ q: '¿Qué Pokémon es la evolución de Charmeleon?', a: ['charizard'] },
{ q: '¿Qué Pokémon es la evolución de Squirtle?', a: ['wartortle'] },
{ q: '¿Qué Pokémon es la evolución de Wartortle?', a: ['blastoise'] },
{ q: '¿Qué tipo de Pokémon es Pikachu?', a: ['electrico'] },
{ q: '¿Qué tipo de Pokémon es Charmander?', a: ['fuego'] },
{ q: '¿Qué tipo de Pokémon es Squirtle?', a: ['agua'] },
{ q: '¿Qué tipo de Pokémon es Bulbasaur?', a: ['planta'] },

{ q: '¿Quién es el hermano de Mario?', a: ['luigi'] },
{ q: '¿Cómo se llama el dinosaurio amigo de Mario?', a: ['yoshi'] },
{ q: '¿Quién es el enemigo principal de Kirby?', a: ['rey dedede', 'dedede'] },
{ q: '¿Qué color tiene Kirby normalmente?', a: ['rosa'] },
{ q: '¿Cómo se llama el protagonista de Metroid?', a: ['samus'] },
{ q: '¿Cómo se llama el protagonista de Halo?', a: ['master chief'] },
{ q: '¿Qué personaje usa una llave espada?', a: ['sora'] },
{ q: '¿Qué saga tiene chocobos?', a: ['final fantasy'] },
{ q: '¿Qué saga tiene pokebolas?', a: ['pokemon'] },
{ q: '¿Qué juego tiene aldeanos con nariz grande?', a: ['minecraft'] },

{ q: '¿Quién es el padre de Goku?', a: ['bardock'] },
{ q: '¿Quién es el hijo mayor de Goku?', a: ['gohan'] },
{ q: '¿Quién es el hijo menor de Goku?', a: ['goten'] },
{ q: '¿Quién es el príncipe de los saiyajin?', a: ['vegeta'] },
{ q: '¿Cómo se llama el hermano de Goku?', a: ['raditz'] },
{ q: '¿Quién entrenó a Naruto cuando era niño?', a: ['kakashi'] },
{ q: '¿Cómo se llama el zorro dentro de Naruto?', a: ['kurama'] },
{ q: '¿Quién es el capitán de los Sombrero de Paja?', a: ['luffy'] },
{ q: '¿Cómo se llama el espadachín de One Piece?', a: ['zoro'] },
{ q: '¿Cómo se llama el cocinero de One Piece?', a: ['sanji'] },

{ q: '¿Qué superhéroe es conocido como el Hombre de Acero?', a: ['superman'] },
{ q: '¿Qué héroe usa un martillo llamado Mjolnir?', a: ['thor'] },
{ q: '¿Qué héroe se transforma cuando se enoja?', a: ['hulk'] },
{ q: '¿Qué héroe usa un traje de vibranio?', a: ['black panther'] },
{ q: '¿Qué héroe es rey de Wakanda?', a: ['black panther', 'tchalla'] },
{ q: '¿Quién es el archienemigo de Batman?', a: ['joker'] },
{ q: '¿Qué héroe corre a super velocidad en DC?', a: ['flash'] },
{ q: '¿Qué héroe puede hablar con peces?', a: ['aquaman'] },
{ q: '¿Qué heroína usa el lazo de la verdad?', a: ['wonder woman'] },
{ q: '¿Qué héroe viene del planeta Krypton?', a: ['superman'] },

{ q: '¿Cuál es la bandera con una hoja de arce?', a: ['canada'] },
{ q: '¿Cuál es la bandera con un sol en el centro?', a: ['argentina'] },
{ q: '¿Cuál es la bandera con un círculo rojo?', a: ['japon'] },
{ q: '¿Cuál es la bandera verde con luna y estrella blanca?', a: ['pakistan'] },
{ q: '¿Cuál es la bandera con una cruz blanca sobre fondo rojo?', a: ['suiza'] },
{ q: '¿Qué país tiene una bandera roja con estrellas amarillas?', a: ['china'] },
{ q: '¿Qué país tiene una bandera azul y amarilla?', a: ['ucrania'] },
{ q: '¿Qué país tiene una bandera verde, amarilla y azul?', a: ['brasil'] },
{ q: '¿Qué país tiene una bandera negra, roja y amarilla?', a: ['alemania'] },
{ q: '¿Qué país tiene una bandera tricolor verde, blanco y rojo?', a: ['italia'] },

{ q: '¿Quién era el dios del trueno en la mitología nórdica?', a: ['thor'] },
{ q: '¿Quién era el dios principal del Olimpo?', a: ['zeus'] },
{ q: '¿Quién era el dios del mar en Grecia?', a: ['poseidon'] },
{ q: '¿Quién era el dios del inframundo?', a: ['hades'] },
{ q: '¿Quién era la diosa de la sabiduría?', a: ['atenea'] },
{ q: '¿Quién era el mensajero de los dioses?', a: ['hermes'] },
{ q: '¿Quién era el dios egipcio con cabeza de chacal?', a: ['anubis'] },
{ q: '¿Quién era el dios del Sol en Egipto?', a: ['ra'] },
{ q: '¿Cómo se llama el martillo de Thor en la mitología?', a: ['mjolnir'] },
{ q: '¿Cómo se llama el caballo de ocho patas de Odín?', a: ['sleipnir'] },

{ q: '¿Qué país ganó el Mundial 2018?', a: ['francia'] },
{ q: '¿Qué país ganó el Mundial 2014?', a: ['alemania'] },
{ q: '¿Qué país ganó el Mundial 2010?', a: ['espana'] },
{ q: '¿Cuántos jugadores tiene un equipo de baloncesto en cancha?', a: ['5', 'cinco'] },
{ q: '¿En qué deporte destaca LeBron James?', a: ['baloncesto', 'basket'] },
{ q: '¿En qué deporte destacó Kobe Bryant?', a: ['baloncesto', 'basket'] },
{ q: '¿Qué país es famoso por el sumo?', a: ['japon'] },
{ q: '¿Qué deporte practica Tiger Woods?', a: ['golf'] },
{ q: '¿Qué deporte practica Lewis Hamilton?', a: ['formula 1'] },
{ q: '¿Qué deporte practica Novak Djokovic?', a: ['tenis'] },

{ q: '¿Qué empresa creó Instagram?', a: ['meta', 'facebook'] },
{ q: '¿Qué empresa creó WhatsApp?', a: ['meta', 'facebook'] },
{ q: '¿Qué empresa desarrolla Windows?', a: ['microsoft'] },
{ q: '¿Qué empresa desarrolla Chrome?', a: ['google'] },
{ q: '¿Qué empresa desarrolla el iPhone?', a: ['apple'] },
{ q: '¿Qué empresa creó TikTok?', a: ['bytedance'] },
{ q: '¿Qué empresa creó YouTube?', a: ['google'] },
{ q: '¿Qué empresa creó Gmail?', a: ['google'] },
{ q: '¿Qué empresa creó Xbox?', a: ['microsoft'] },
{ q: '¿Qué empresa creó PlayStation?', a: ['sony'] },

{ q: '¿Qué idioma se habla principalmente en Argentina?', a: ['espanol'] },
{ q: '¿Qué idioma se habla principalmente en Brasil?', a: ['portugues'] },
{ q: '¿Qué idioma se habla principalmente en Rusia?', a: ['ruso'] },
{ q: '¿Qué idioma se habla principalmente en China?', a: ['chino', 'mandarin'] },
{ q: '¿Qué idioma se habla principalmente en Corea del Sur?', a: ['coreano'] },
{ q: '¿Qué idioma se habla principalmente en Italia?', a: ['italiano'] },
{ q: '¿Qué idioma se habla principalmente en Alemania?', a: ['aleman'] },
{ q: '¿Qué idioma se habla principalmente en Francia?', a: ['frances'] },
{ q: '¿Qué idioma se habla principalmente en Japón?', a: ['japones'] },
{ q: '¿Qué idioma se habla principalmente en Turquía?', a: ['turco'] }, 
  { q: '¿Qué Pokémon es conocido como el Pokémon ratón?', a: ['pikachu'] },
{ q: '¿Qué Pokémon tiene una llama en la cola?', a: ['charmander'] },
{ q: '¿Qué Pokémon parece una tortuga azul?', a: ['squirtle'] },
{ q: '¿Qué Pokémon tiene una flor en la espalda al evolucionar?', a: ['venusaur'] },
{ q: '¿Qué Pokémon legendario representa el mar?', a: ['kyogre'] },
{ q: '¿Qué Pokémon legendario representa la tierra?', a: ['groudon'] },
{ q: '¿Qué Pokémon legendario representa el cielo?', a: ['rayquaza'] },
{ q: '¿Qué Pokémon es la mascota de Pokémon Amarillo?', a: ['pikachu'] },
{ q: '¿Qué Pokémon usa una cuchara para pelear?', a: ['alakazam'] },
{ q: '¿Qué Pokémon tiene tres cabezas?', a: ['dodrio'] },

{ q: '¿Qué Pokémon es conocido como el rey de los mares?', a: ['kyogre'] },
{ q: '¿Qué Pokémon puede transformarse en otros?', a: ['ditto'] },
{ q: '¿Qué Pokémon tiene forma de pokebola?', a: ['voltorb'] },
{ q: '¿Qué Pokémon es un dragón naranja con alas?', a: ['charizard'] },
{ q: '¿Qué Pokémon es un tiburón dragón?', a: ['garchomp'] },
{ q: '¿Qué Pokémon es la evolución final de Treecko?', a: ['sceptile'] },
{ q: '¿Qué Pokémon es la evolución final de Torchic?', a: ['blaziken'] },
{ q: '¿Qué Pokémon es la evolución final de Mudkip?', a: ['swampert'] },
{ q: '¿Qué Pokémon es el dios del universo según el lore?', a: ['arceus'] },
{ q: '¿Qué Pokémon representa el tiempo?', a: ['dialga'] },

{ q: '¿Qué Pokémon representa el espacio?', a: ['palkia'] },
{ q: '¿Qué Pokémon representa la antimateria?', a: ['giratina'] },
{ q: '¿Qué Pokémon duerme casi todo el tiempo?', a: ['snorlax'] },
{ q: '¿Qué Pokémon es un pato amarillo?', a: ['psyduck'] },
{ q: '¿Qué Pokémon es famoso por decir su propio nombre?', a: ['pikachu'] },
{ q: '¿Qué Pokémon tiene una gran cola en forma de rayo?', a: ['raichu'] },
{ q: '¿Qué Pokémon es una serpiente morada?', a: ['ekans'] },
{ q: '¿Qué Pokémon es un gato elegante de tipo normal?', a: ['persian'] },
{ q: '¿Qué Pokémon parece una planta carnívora?', a: ['victreebel'] },
{ q: '¿Qué Pokémon tiene una concha en el vientre?', a: ['oshawott'] },

{ q: '¿Quién fue el Cuarto Hokage?', a: ['minato'] },
{ q: '¿Quién fue el Tercer Hokage?', a: ['hiruzen'] },
{ q: '¿Quién fue el Quinto Hokage?', a: ['tsunade'] },
{ q: '¿Quién fue el Sexto Hokage?', a: ['kakashi'] },
{ q: '¿Quién fue el Séptimo Hokage?', a: ['naruto'] },
{ q: '¿A qué clan pertenece Naruto?', a: ['uzumaki'] },
{ q: '¿A qué clan pertenece Sasuke?', a: ['uchiha'] },
{ q: '¿Quién es el hermano mayor de Sasuke?', a: ['itachi'] },
{ q: '¿Quién entrenó a Jiraiya?', a: ['hiruzen'] },
{ q: '¿Quién entrenó a Minato?', a: ['jiraiya'] },

{ q: '¿Cómo se llama el equipo de Naruto, Sasuke y Sakura?', a: ['equipo 7'] },
{ q: '¿Quién lideraba el Equipo 7?', a: ['kakashi'] },
{ q: '¿Quién controla la arena en Naruto?', a: ['gaara'] },
{ q: '¿Quién es el padre de Gaara?', a: ['rasa'] },
{ q: '¿Cómo se llama la aldea de Gaara?', a: ['arena'] },
{ q: '¿Quién posee al Shukaku?', a: ['gaara'] },
{ q: '¿Quién posee al Hachibi?', a: ['killer bee'] },
{ q: '¿Quién posee al Kyubi?', a: ['naruto'] },
{ q: '¿Cómo se llama la organización de villanos principal?', a: ['akatsuki'] },
{ q: '¿Quién fundó Akatsuki junto a Yahiko?', a: ['nagato'] },

{ q: '¿Quién usa la técnica Chidori?', a: ['sasuke'] },
{ q: '¿Quién creó el Rasengan?', a: ['minato'] },
{ q: '¿Quién invoca sapos gigantes?', a: ['jiraiya'] },
{ q: '¿Quién es conocido como el Sabio Pervertido?', a: ['jiraiya'] },
{ q: '¿Cómo se llama la hija de Naruto?', a: ['himawari'] },

{ q: '¿Cómo se llama el barco de Luffy al inicio?', a: ['going merry'] },
{ q: '¿Cómo se llama el segundo barco de los Sombrero de Paja?', a: ['thousand sunny'] },
{ q: '¿Cómo se llama el navegante de la tripulación?', a: ['nami'] },
{ q: '¿Cómo se llama el francotirador de la tripulación?', a: ['usopp'] },
{ q: '¿Cómo se llama el médico de la tripulación?', a: ['chopper'] },
{ q: '¿Cómo se llama la arqueóloga de la tripulación?', a: ['robin'] },
{ q: '¿Cómo se llama el músico de la tripulación?', a: ['brook'] },
{ q: '¿Cómo se llama el carpintero de la tripulación?', a: ['franky'] },
{ q: '¿Cómo se llama el timonel de la tripulación?', a: ['jinbe'] },
{ q: '¿Cómo se llama el espadachín de cabello verde?', a: ['zoro'] },

{ q: '¿Cómo se llama el emperador pelirrojo?', a: ['shanks'] },
{ q: '¿Cómo se llama el abuelo de Luffy?', a: ['garp'] },
{ q: '¿Cómo se llama el padre de Luffy?', a: ['dragon'] },
{ q: '¿Cómo se llama el hermano de fuego de Luffy?', a: ['ace'] },
{ q: '¿Cómo se llama el otro hermano de Luffy?', a: ['sabo'] },
{ q: '¿Qué fruta comió Luffy?', a: ['gomu gomu no mi', 'hito hito no mi modelo nika'] },
{ q: '¿Qué fruta comió Ace?', a: ['mera mera no mi'] },
{ q: '¿Qué fruta comió Barbanegra?', a: ['yami yami no mi'] },
{ q: '¿Cómo se llama el rey de los piratas?', a: ['gol d roger', 'roger'] },
{ q: '¿Cómo se llama el tesoro más buscado?', a: ['one piece'] },

{ q: '¿Cómo se llama la prisión submarina?', a: ['impel down'] },
{ q: '¿Cómo se llama la guerra donde murió Ace?', a: ['marineford'] },
{ q: '¿Cómo se llama el almirante de magma?', a: ['akainu'] },
{ q: '¿Cómo se llama el almirante de hielo?', a: ['aokiji'] },
{ q: '¿Cómo se llama el almirante de luz?', a: ['kizaru'] },
{ q: '¿Cómo se llama el primer emperador derrotado por Luffy?', a: ['kaido'] },
{ q: '¿Cómo se llama la isla de los hombres pez?', a: ['isla gyojin'] },
{ q: '¿Cómo se llama la princesa sirena?', a: ['shirahoshi'] },
{ q: '¿Cómo se llama el reino de Arabasta?', a: ['arabasta'] },
{ q: '¿Cómo se llama el villano principal de Arabasta?', a: ['crocodile'] },

{ q: '¿Cómo se llama el villano principal de Skypiea?', a: ['enel'] },
{ q: '¿Cómo se llama la isla del cielo?', a: ['skypiea'] },
{ q: '¿Cómo se llama el científico de Vegapunk?', a: ['vegapunk'] },
{ q: '¿Cómo se llama el espadachín más fuerte del mundo?', a: ['mihawk'] },
{ q: '¿Cómo se llama la emperatriz amazona enamorada de Luffy?', a: ['boa hancock'] },
{ q: '¿Cómo se llama el perro zombie de Thriller Bark?', a: ['cerberus'] },
{ q: '¿Cómo se llama el esqueleto músico?', a: ['brook'] },
{ q: '¿Cómo se llama el reno médico?', a: ['chopper'] },
{ q: '¿Cómo se llama el cyborg de la tripulación?', a: ['franky'] },
{ q: '¿Cómo se llama el chef de ceja rizada?', a: ['sanji'] }, 
  // 🟠 DRAGON BALL (25)

{ q: '¿Cómo se llama el abuelo adoptivo de Goku?', a: ['gohan'] },
{ q: '¿Cómo se llama la esposa de Goku?', a: ['milk', 'chi chi', 'chichi'] },
{ q: '¿Cómo se llama el hijo mayor de Goku?', a: ['gohan'] },
{ q: '¿Cómo se llama el hijo menor de Goku?', a: ['goten'] },
{ q: '¿Cómo se llama el príncipe de los saiyajin?', a: ['vegeta'] },
{ q: '¿Cómo se llama la esposa de Vegeta?', a: ['bulma'] },
{ q: '¿Cómo se llama el hijo de Vegeta?', a: ['trunks'] },
{ q: '¿Cómo se llama el namekiano amigo de Goku?', a: ['piccolo'] },
{ q: '¿Cómo se llama el androide perfecto?', a: ['cell'] },
{ q: '¿Cómo se llama el monstruo rosado que absorbe enemigos?', a: ['majin buu', 'buu'] },

{ q: '¿Cómo se llama el emperador del mal del universo 7?', a: ['freezer', 'frieza'] },
{ q: '¿Cómo se llama el padre de Goku?', a: ['bardock'] },
{ q: '¿Cómo se llama el hermano de Goku?', a: ['raditz'] },
{ q: '¿Cómo se llama el dios de la destrucción del universo 7?', a: ['beerus'] },
{ q: '¿Cómo se llama el ángel acompañante de Beerus?', a: ['whis'] },
{ q: '¿Cómo se llama el rey de todo en Dragon Ball Super?', a: ['zeno'] },
{ q: '¿Cómo se llama la técnica de teletransporte de Goku?', a: ['shunkan ido'] },
{ q: '¿Cómo se llama la técnica más famosa de Goku?', a: ['kamehameha'] },
{ q: '¿Cómo se llama el maestro tortuga?', a: ['roshi', 'maestro roshi'] },
{ q: '¿Cómo se llama el mejor amigo humano de Goku?', a: ['krilin'] },

{ q: '¿Cómo se llama el torneo entre universos de Dragon Ball Super?', a: ['torneo del poder'] },
{ q: '¿Cómo se llama el universo de Jiren?', a: ['universo 11'] },
{ q: '¿Cómo se llama el guerrero más fuerte del universo 11?', a: ['jiren'] },
{ q: '¿Cómo se llama la fusión de Goku y Vegeta mediante danza?', a: ['gogeta'] },
{ q: '¿Cómo se llama la fusión usando pendientes potara?', a: ['vegito'] },

// 🦸 MARVEL Y DC (25)

{ q: '¿Nombre real de Hulk?', a: ['bruce banner'] },
{ q: '¿Nombre real de Thor?', a: ['thor odinson'] },
{ q: '¿Nombre real de Black Widow?', a: ['natasha romanoff'] },
{ q: '¿Nombre real de Hawkeye?', a: ['clint barton'] },
{ q: '¿Nombre real de Doctor Strange?', a: ['stephen strange'] },
{ q: '¿Nombre real de Black Panther?', a: ['tchalla'] },
{ q: '¿Nombre real de Ant-Man?', a: ['scott lang'] },
{ q: '¿Nombre real de Star-Lord?', a: ['peter quill'] },
{ q: '¿Quién creó Ultron?', a: ['tony stark'] },
{ q: '¿Qué gema controla el tiempo?', a: ['gema del tiempo'] },

{ q: '¿Qué gema controla la mente?', a: ['gema de la mente'] },
{ q: '¿Qué gema controla el espacio?', a: ['gema del espacio'] },
{ q: '¿Qué gema controla el poder?', a: ['gema del poder'] },
{ q: '¿Qué gema controla la realidad?', a: ['gema de la realidad'] },
{ q: '¿Qué gema controla el alma?', a: ['gema del alma'] },
{ q: '¿Ciudad protegida por Batman?', a: ['gotham'] },
{ q: '¿Ciudad protegida por Superman?', a: ['metropolis'] },
{ q: '¿Nombre real de Batman?', a: ['bruce wayne'] },
{ q: '¿Nombre real de Superman?', a: ['clark kent'] },
{ q: '¿Nombre real de Wonder Woman?', a: ['diana prince'] },

{ q: '¿Nombre real de Flash más conocido?', a: ['barry allen'] },
{ q: '¿Nombre real de Aquaman?', a: ['arthur curry'] },
{ q: '¿Principal enemigo de Superman?', a: ['lex luthor'] },
{ q: '¿Principal enemigo de Flash?', a: ['reverse flash'] },
{ q: '¿Principal enemigo de Green Lantern?', a: ['sinestro'] },

// ⛏️ MINECRAFT, GTA, VALORANT (25)

{ q: '¿Material más resistente de Minecraft?', a: ['netherite'] },
{ q: '¿Mineral rojo usado para circuitos?', a: ['redstone'] },
{ q: '¿Dimensión infernal de Minecraft?', a: ['nether'] },
{ q: '¿Jefe final de Minecraft?', a: ['dragon del end', 'ender dragon'] },
{ q: '¿Criatura negra que se teletransporta?', a: ['enderman'] },
{ q: '¿Criatura que explota al acercarse?', a: ['creeper'] },
{ q: '¿Animal que da cuero en Minecraft?', a: ['vaca'] },
{ q: '¿Herramienta para picar piedra?', a: ['pico'] },
{ q: '¿Objeto usado para dormir en Minecraft?', a: ['cama'] },
{ q: '¿Nombre de la ciudad principal en GTA San Andreas?', a: ['los santos'] },

{ q: '¿Nombre del protagonista de GTA San Andreas?', a: ['cj', 'carl johnson'] },
{ q: '¿Nombre del protagonista de GTA V rubio?', a: ['trevor'] },
{ q: '¿Nombre del protagonista de GTA V empresario?', a: ['michael'] },
{ q: '¿Nombre del protagonista de GTA V joven?', a: ['franklin'] },
{ q: '¿Ciudad inspirada en Nueva York en GTA?', a: ['liberty city'] },
{ q: '¿Agente japonesa de Valorant?', a: ['jett'] },
{ q: '¿Agente de fuego de Valorant?', a: ['phoenix'] },
{ q: '¿Agente mexicana de Valorant?', a: ['reyna'] },
{ q: '¿Agente alemana de Valorant?', a: ['killjoy'] },
{ q: '¿Agente que usa flechas rastreadoras?', a: ['sova'] },

{ q: '¿Agente controlador de humo tóxico?', a: ['viper'] },
{ q: '¿Agente francés que usa trampas?', a: ['chamber'] },
{ q: '¿Agente que revive compañeros?', a: ['sage'] },
{ q: '¿Agente que usa portales?', a: ['yoru'] },
{ q: '¿Nombre del mapa tropical de Valorant?', a: ['breeze'] },

// 🔬 CIENCIA Y CULTURA GENERAL (25)

{ q: '¿Cuál es el planeta más caliente del sistema solar?', a: ['venus'] },
{ q: '¿Cuál es el planeta más frío del sistema solar?', a: ['urano'] },
{ q: '¿Qué planeta tiene el día más largo?', a: ['venus'] },
{ q: '¿Qué planeta tiene más lunas conocidas?', a: ['saturno'] },
{ q: '¿Qué órgano produce insulina?', a: ['pancreas'] },
{ q: '¿Qué órgano almacena la bilis?', a: ['vesicula'] },
{ q: '¿Qué vitamina obtenemos principalmente del sol?', a: ['vitamina d'] },
{ q: '¿Qué metal es líquido a temperatura ambiente?', a: ['mercurio'] },
{ q: '¿Qué elemento químico tiene símbolo O?', a: ['oxigeno'] },
{ q: '¿Qué elemento químico tiene símbolo H?', a: ['hidrogeno'] },

{ q: '¿Qué elemento químico tiene símbolo Na?', a: ['sodio'] },
{ q: '¿Qué elemento químico tiene símbolo K?', a: ['potasio'] },
{ q: '¿Qué país inventó la pizza moderna?', a: ['italia'] },
{ q: '¿Qué país inventó el sushi?', a: ['japon'] },
{ q: '¿Qué país inventó el tango?', a: ['argentina'] },
{ q: '¿Qué idioma se habla en Austria?', a: ['aleman'] },
{ q: '¿Qué idioma se habla en Suiza además del alemán?', a: ['frances'] },
{ q: '¿Qué continente tiene más países?', a: ['africa'] },
{ q: '¿Qué mar separa Europa y África?', a: ['mediterraneo'] },
{ q: '¿Qué instrumento mide terremotos?', a: ['sismografo'] },

{ q: '¿Cómo se llama la ciencia que estudia los volcanes?', a: ['vulcanologia'] },
{ q: '¿Cómo se llama la ciencia que estudia los fósiles?', a: ['paleontologia'] },
{ q: '¿Cómo se llama la ciencia que estudia los insectos?', a: ['entomologia'] },
{ q: '¿Cómo se llama la ciencia que estudia las estrellas?', a: ['astronomia'] },
{ q: '¿Cómo se llama la ciencia que estudia los océanos?', a: ['oceanografia'] },
  // 🏛️ MITOLOGÍA (25)

{ q: '¿Dios del trueno en la mitología nórdica?', a: ['thor'] },
{ q: '¿Dios principal de la mitología griega?', a: ['zeus'] },
{ q: '¿Dios del mar en la mitología griega?', a: ['poseidon'] },
{ q: '¿Dios del inframundo griego?', a: ['hades'] },
{ q: '¿Diosa de la sabiduría griega?', a: ['atenea'] },
{ q: '¿Dios de la guerra griego?', a: ['ares'] },
{ q: '¿Mensajero de los dioses griegos?', a: ['hermes'] },
{ q: '¿Diosa del amor griega?', a: ['afrodita'] },
{ q: '¿Padre de Thor en la mitología nórdica?', a: ['odin'] },
{ q: '¿Lobo gigante del Ragnarok?', a: ['fenrir'] },

{ q: '¿Serpiente gigante enemiga de Thor?', a: ['jormungandr'] },
{ q: '¿Puente arcoíris de Asgard?', a: ['bifrost'] },
{ q: '¿Martillo de Thor?', a: ['mjolnir'] },
{ q: '¿Caballo de ocho patas de Odín?', a: ['sleipnir'] },
{ q: '¿Héroe griego que venció a Medusa?', a: ['perseo'] },
{ q: '¿Héroe griego de la Ilíada?', a: ['aquiles'] },
{ q: '¿Rey de Ítaca?', a: ['odiseo'] },
{ q: '¿Monstruo con cabeza de toro?', a: ['minotauro'] },
{ q: '¿Criatura mitad águila mitad león?', a: ['grifo'] },
{ q: '¿Ave que renace de sus cenizas?', a: ['fenix'] },

{ q: '¿Caballo con un cuerno?', a: ['unicornio'] },
{ q: '¿Monstruo de muchas cabezas vencido por Hércules?', a: ['hidra'] },
{ q: '¿Héroe conocido por su fuerza sobrehumana?', a: ['hercules'] },
{ q: '¿Diosa cazadora griega?', a: ['artemisa'] },
{ q: '¿Dios del sol griego?', a: ['apolo'] },

// 🚩 BANDERAS Y PAÍSES (25)

{ q: '¿Qué país tiene una hoja de arce en su bandera?', a: ['canada'] },
{ q: '¿Qué país tiene un sol en su bandera y está al sur de Brasil?', a: ['argentina'] },
{ q: '¿Qué país tiene una bandera roja con una luna creciente?', a: ['turquia'] },
{ q: '¿Qué país tiene una bandera con un dragón rojo?', a: ['gales'] },
{ q: '¿Qué país tiene una bandera con una cruz roja sobre fondo blanco?', a: ['suiza'] },
{ q: '¿Qué país tiene una bandera verde con un rombo amarillo?', a: ['brasil'] },
{ q: '¿Qué país tiene una bandera roja con cinco estrellas amarillas?', a: ['china'] },
{ q: '¿Qué país tiene una bandera con barras y estrellas?', a: ['estados unidos'] },
{ q: '¿Qué país tiene una bandera roja y blanca con un círculo rojo?', a: ['japon'] },
{ q: '¿Qué país tiene una bandera azul y blanca con una estrella de David?', a: ['israel'] },

{ q: '¿Qué país tiene una bandera negra, roja y amarilla?', a: ['alemania'] },
{ q: '¿Qué país tiene una bandera azul, blanca y roja vertical?', a: ['francia'] },
{ q: '¿Qué país tiene una bandera verde, blanca y roja vertical?', a: ['italia'] },
{ q: '¿Qué país tiene una bandera roja y amarilla con escudo?', a: ['espana'] },
{ q: '¿Qué país tiene una bandera con una unión de cruces llamada Union Jack?', a: ['reino unido'] },

{ q: '¿Qué país tiene una bandera con cedro verde?', a: ['libano'] },
{ q: '¿Qué país tiene una bandera con un sol naciente?', a: ['japon'] },
{ q: '¿Qué país tiene una bandera azul con cruz amarilla?', a: ['suecia'] },
{ q: '¿Qué país tiene una bandera roja con cruz blanca escandinava?', a: ['dinamarca'] },
{ q: '¿Qué país tiene una bandera azul, amarilla y roja?', a: ['colombia'] },

{ q: '¿Qué país tiene una bandera roja y blanca con dos franjas?', a: ['peru'] },
{ q: '¿Qué país tiene una bandera azul y blanca con cinco estrellas?', a: ['honduras'] },
{ q: '¿Qué país tiene una bandera azul con una cruz blanca?', a: ['finlandia'] },
{ q: '¿Qué país tiene una bandera verde con media luna blanca?', a: ['pakistan'] },
{ q: '¿Qué país tiene una bandera roja con una estrella verde?', a: ['marruecos'] },

// 💡 INVENTOS Y DESCUBRIMIENTOS (25)

{ q: '¿Quién inventó la bombilla eléctrica práctica?', a: ['thomas edison', 'edison'] },
{ q: '¿Quién inventó el teléfono?', a: ['alexander graham bell', 'graham bell'] },
{ q: '¿Quién inventó la imprenta moderna?', a: ['gutenberg'] },
{ q: '¿Quién inventó la radio?', a: ['marconi'] },
{ q: '¿Quién desarrolló la teoría de la relatividad?', a: ['einstein'] },

{ q: '¿Quién descubrió la gravedad al observar una manzana?', a: ['newton'] },
{ q: '¿Quién descubrió la penicilina?', a: ['alexander fleming', 'fleming'] },
{ q: '¿Quién pintó la Capilla Sixtina?', a: ['miguel angel', 'michelangelo'] },
{ q: '¿Quién inventó el avión?', a: ['hermanos wright', 'wright'] },
{ q: '¿Quién creó la World Wide Web?', a: ['tim berners lee'] },

{ q: '¿Qué inventor está asociado con Tesla AC?', a: ['nikola tesla'] },
{ q: '¿Quién descubrió América para Europa?', a: ['cristobal colon'] },
{ q: '¿Qué científico propuso el heliocentrismo?', a: ['copernico'] },
{ q: '¿Quién observó los planetas con telescopio y apoyó el heliocentrismo?', a: ['galileo'] },
{ q: '¿Quién formuló las leyes del movimiento?', a: ['newton'] },

{ q: '¿Qué invento permite observar objetos lejanos en el espacio?', a: ['telescopio'] },
{ q: '¿Qué invento permite observar microorganismos?', a: ['microscopio'] },
{ q: '¿Qué invento sirve para medir el tiempo?', a: ['reloj'] },
{ q: '¿Qué invento sirve para orientarse usando el norte magnético?', a: ['brujula'] },
{ q: '¿Qué invento permitió imprimir libros masivamente?', a: ['imprenta'] },

{ q: '¿Qué invento usa ruedas dentadas para mover mecanismos?', a: ['engranaje'] },
{ q: '¿Qué invento revolucionó el transporte en el siglo XIX?', a: ['ferrocarril'] },
{ q: '¿Qué invento transmite voz a distancia?', a: ['telefono'] },
{ q: '¿Qué invento transmite imágenes en movimiento?', a: ['television'] },
{ q: '¿Qué invento conecta computadoras globalmente?', a: ['internet'] },

// 🚀 ESPACIO Y CURIOSIDADES (25)

{ q: '¿Cuál es la estrella más cercana a la Tierra?', a: ['sol'] },
{ q: '¿Cuál es el segundo planeta del sistema solar?', a: ['venus'] },
{ q: '¿Cuál es el cuarto planeta del sistema solar?', a: ['marte'] },
{ q: '¿Cuál es el sexto planeta del sistema solar?', a: ['saturno'] },
{ q: '¿Cuál es el séptimo planeta del sistema solar?', a: ['urano'] },

{ q: '¿Cuál es el octavo planeta del sistema solar?', a: ['neptuno'] },
{ q: '¿Qué planeta es conocido como gigante gaseoso?', a: ['jupiter'] },
{ q: '¿Qué planeta tiene la Gran Mancha Roja?', a: ['jupiter'] },
{ q: '¿Qué planeta tiene anillos más famosos?', a: ['saturno'] },
{ q: '¿Qué misión llevó humanos por primera vez a la Luna?', a: ['apollo 11'] },

{ q: '¿Quién fue el segundo hombre en caminar sobre la Luna?', a: ['buzz aldrin'] },
{ q: '¿Qué agencia espacial pertenece a Estados Unidos?', a: ['nasa'] },
{ q: '¿Qué agencia espacial pertenece a Europa?', a: ['esa'] },
{ q: '¿Qué planeta recibe el nombre del dios romano de la guerra?', a: ['marte'] },
{ q: '¿Qué planeta recibe el nombre del dios romano del mar?', a: ['neptuno'] },

{ q: '¿Cómo se llama nuestra galaxia?', a: ['via lactea'] },
{ q: '¿Cómo se llama la galaxia más cercana grande a la nuestra?', a: ['andromeda'] },
{ q: '¿Qué fenómeno ocurre cuando la Luna tapa al Sol?', a: ['eclipse solar'] },
{ q: '¿Qué fenómeno ocurre cuando la Tierra tapa la Luna?', a: ['eclipse lunar'] },
{ q: '¿Cómo se llama una roca que cae desde el espacio?', a: ['meteorito'] },

{ q: '¿Cómo se llama la capa visible del Sol?', a: ['fotosfera'] },
{ q: '¿Qué planeta tarda más en orbitar el Sol?', a: ['neptuno'] },
{ q: '¿Qué planeta tarda menos en orbitar el Sol?', a: ['mercurio'] },
{ q: '¿Qué cuerpo celeste ilumina las noches terrestres?', a: ['luna'] },
{ q: '¿Qué fuerza mantiene a los planetas orbitando?', a: ['gravedad'] }

);

// ✅ Limpia preguntas repetidas por texto para evitar duplicados exactos
const preguntasUnicas = new Map();

for (const item of preguntas) {
  const key = normalize(item.q);

  if (!preguntasUnicas.has(key)) {
    preguntasUnicas.set(key, item);
  }
}

preguntas.length = 0;
preguntas.push(...preguntasUnicas.values());

function getQuestion() {
  if (used.size >= preguntas.length) {
    used.clear();
  }

  let index;

  do {
    index = Math.floor(Math.random() * preguntas.length);
  } while (used.has(index));

  used.add(index);

  const item = preguntas[index];

  return {
    q: item.q,
    answers: item.a.map(normalize)
  };
}

function start(chatId, timeout = null) {
  if (current) return null;

  const q = getQuestion();

  current = {
    chat: chatId,
    question: q.q,
    answers: q.answers,
    answer: q.answers[0],
    active: true,
    startedAt: Date.now(),
    timeout
  };

  return current;
}

function next() {
  if (!current) return null;

  const q = getQuestion();

  current.question = q.q;
  current.answers = q.answers;
  current.answer = q.answers[0];
  current.startedAt = Date.now();

  return current;
}

function stop() {
  if (current?.timeout) clearTimeout(current.timeout);
  current = null;
}

function get() {
  return current;
}

function check(text = '') {
  if (!current) return false;

  const userText = normalize(text);

  return current.answers.some(answer => {
    if (!answer) return false;
    return userText === answer || userText.includes(answer);
  });
}

function forceSet(data = {}) {
  current = {
    chat: data.chat || null,
    question: data.question || '',
    answers: Array.isArray(data.answers)
      ? data.answers.map(normalize)
      : [normalize(data.answer || '')],
    answer: normalize(data.answer || ''),
    active: true,
    startedAt: Date.now(),
    timeout: data.timeout || null
  };

  return current;
}

module.exports = {
  preguntas,
  normalize,
  start,
  next,
  stop,
  get,
  check,
  forceSet
};
